import type { Room } from "@/app/providers/workflow-store";

export const mockRooms: Room[] = [
  {
    id: "room-1",
    code: "P.101",
    area: "Tầng 1",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 4000000,
    beds: [
      { id: "bed-101-1", code: "G.101-1", status: "available" },
      { id: "bed-101-2", code: "G.101-2", status: "available" },
      { id: "bed-101-3", code: "G.101-3", status: "available" },
      { id: "bed-101-4", code: "G.101-4", status: "occupied" },
    ],
    assets: [
      { id: "ast-101-1", name: "Giường tầng", quantity: 2, condition: "Tốt" },
      { id: "ast-101-2", name: "Bàn học", quantity: 4, condition: "Tốt" },
      { id: "ast-101-3", name: "Ghế xoay", quantity: 4, condition: "Tốt" },
      { id: "ast-101-4", name: "Tủ quần áo", quantity: 2, condition: "Tốt" },
      { id: "ast-101-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-101-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
    ],
    status: "partially_available",
  },
  {
    id: "room-2",
    code: "P.102",
    area: "Tầng 1",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 4200000,
    beds: [
      { id: "bed-102-1", code: "G.102-1", status: "available" },
      { id: "bed-102-2", code: "G.102-2", status: "available" },
      { id: "bed-102-3", code: "G.102-3", status: "available" },
      { id: "bed-102-4", code: "G.102-4", status: "available" },
    ],
    assets: [
      { id: "ast-102-1", name: "Giường tầng", quantity: 2, condition: "Tốt" },
      { id: "ast-102-2", name: "Bàn học", quantity: 4, condition: "Tốt" },
      { id: "ast-102-3", name: "Ghế xoay", quantity: 4, condition: "Tốt" },
      { id: "ast-102-4", name: "Tủ quần áo", quantity: 2, condition: "Mới" },
      { id: "ast-102-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-102-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
    ],
    status: "available",
  },
  {
    id: "room-3",
    code: "P.203",
    area: "Tầng 2",
    type: "6 người",
    maxCapacity: 6,
    basePrice: 3500000,
    beds: [
      { id: "bed-203-1", code: "G.203-1", status: "available" },
      { id: "bed-203-2", code: "G.203-2", status: "deposited" },
      { id: "bed-203-3", code: "G.203-3", status: "occupied" },
      { id: "bed-203-4", code: "G.203-4", status: "occupied" },
      { id: "bed-203-5", code: "G.203-5", status: "available" },
      { id: "bed-203-6", code: "G.203-6", status: "maintenance" },
    ],
    assets: [
      { id: "ast-203-1", name: "Giường tầng", quantity: 3, condition: "Tốt" },
      { id: "ast-203-2", name: "Bàn học", quantity: 6, condition: "Tốt" },
      { id: "ast-203-3", name: "Ghế xoay", quantity: 6, condition: "Tốt" },
      { id: "ast-203-4", name: "Tủ quần áo", quantity: 3, condition: "Cũ" },
      { id: "ast-203-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-203-6", name: "Máy nước nóng", quantity: 1, condition: "Cần bảo trì" },
    ],
    status: "partially_available",
  },
  {
    id: "room-4",
    code: "P.208",
    area: "Tầng 2",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 3800000,
    beds: [
      { id: "bed-208-1", code: "G.208-1", status: "occupied" },
      { id: "bed-208-2", code: "G.208-2", status: "occupied" },
      { id: "bed-208-3", code: "G.208-3", status: "occupied" },
      { id: "bed-208-4", code: "G.208-4", status: "occupied" },
    ],
    assets: [
      { id: "ast-208-1", name: "Giường tầng", quantity: 2, condition: "Tốt" },
      { id: "ast-208-2", name: "Bàn học", quantity: 4, condition: "Tốt" },
      { id: "ast-208-3", name: "Ghế xoay", quantity: 4, condition: "Tốt" },
      { id: "ast-208-4", name: "Tủ quần áo", quantity: 2, condition: "Tốt" },
      { id: "ast-208-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
    ],
    status: "full",
  },
  {
    id: "room-5",
    code: "P.305",
    area: "Tầng 3",
    type: "6 người",
    maxCapacity: 6,
    basePrice: 4500000,
    beds: [
      { id: "bed-305-1", code: "G.305-1", status: "available" },
      { id: "bed-305-2", code: "G.305-2", status: "available" },
      { id: "bed-305-3", code: "G.305-3", status: "available" },
      { id: "bed-305-4", code: "G.305-4", status: "available" },
      { id: "bed-305-5", code: "G.305-5", status: "available" },
      { id: "bed-305-6", code: "G.305-6", status: "available" },
    ],
    assets: [
      { id: "ast-305-1", name: "Giường tầng", quantity: 3, condition: "Mới" },
      { id: "ast-305-2", name: "Bàn học", quantity: 6, condition: "Mới" },
      { id: "ast-305-3", name: "Ghế xoay", quantity: 6, condition: "Mới" },
      { id: "ast-305-4", name: "Tủ quần áo", quantity: 3, condition: "Mới" },
      { id: "ast-305-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-305-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
      { id: "ast-305-7", name: "Ban công", quantity: 1, condition: "Tốt" },
    ],
    status: "available",
  },
  {
    id: "room-6",
    code: "P.310",
    area: "Tầng 3",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 4300000,
    beds: [
      { id: "bed-310-1", code: "G.310-1", status: "available" },
      { id: "bed-310-2", code: "G.310-2", status: "available" },
      { id: "bed-310-3", code: "G.310-3", status: "maintenance" },
      { id: "bed-310-4", code: "G.310-4", status: "maintenance" },
    ],
    assets: [
      { id: "ast-310-1", name: "Giường tầng", quantity: 2, condition: "Tốt" },
      { id: "ast-310-2", name: "Bàn học", quantity: 4, condition: "Tốt" },
      { id: "ast-310-3", name: "Ghế xoay", quantity: 4, condition: "Tốt" },
      { id: "ast-310-4", name: "Tủ quần áo", quantity: 2, condition: "Cũ" },
      { id: "ast-310-5", name: "Điều hòa", quantity: 1, condition: "Cần bảo trì" },
    ],
    status: "maintenance",
  },
  {
    id: "room-7",
    code: "P.401",
    area: "Tầng 4",
    type: "2 người",
    maxCapacity: 2,
    basePrice: 5500000,
    beds: [
      { id: "bed-401-1", code: "G.401-1", status: "available" },
      { id: "bed-401-2", code: "G.401-2", status: "available" },
    ],
    assets: [
      { id: "ast-401-1", name: "Giường đơn", quantity: 2, condition: "Mới" },
      { id: "ast-401-2", name: "Bàn học", quantity: 2, condition: "Mới" },
      { id: "ast-401-3", name: "Ghế xoay", quantity: 2, condition: "Mới" },
      { id: "ast-401-4", name: "Tủ quần áo", quantity: 2, condition: "Mới" },
      { id: "ast-401-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-401-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
      { id: "ast-401-7", name: "Tủ lạnh", quantity: 1, condition: "Tốt" },
      { id: "ast-401-8", name: "Ban công", quantity: 1, condition: "Tốt" },
    ],
    status: "available",
  },
  {
    id: "room-8",
    code: "P.405",
    area: "Tầng 4",
    type: "6 người",
    maxCapacity: 6,
    basePrice: 5000000,
    beds: [
      { id: "bed-405-1", code: "G.405-1", status: "deposited" },
      { id: "bed-405-2", code: "G.405-2", status: "deposited" },
      { id: "bed-405-3", code: "G.405-3", status: "deposited" },
      { id: "bed-405-4", code: "G.405-4", status: "available" },
      { id: "bed-405-5", code: "G.405-5", status: "available" },
      { id: "bed-405-6", code: "G.405-6", status: "available" },
    ],
    assets: [
      { id: "ast-405-1", name: "Giường tầng", quantity: 3, condition: "Tốt" },
      { id: "ast-405-2", name: "Bàn học", quantity: 6, condition: "Tốt" },
      { id: "ast-405-3", name: "Ghế xoay", quantity: 6, condition: "Tốt" },
      { id: "ast-405-4", name: "Tủ quần áo", quantity: 3, condition: "Tốt" },
      { id: "ast-405-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-405-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
    ],
    status: "partially_available",
  },
  {
    id: "room-9",
    code: "P.103",
    area: "Tầng 1",
    type: "6 người",
    maxCapacity: 6,
    basePrice: 3600000,
    beds: [
      { id: "bed-103-1", code: "G.103-1", status: "available" },
      { id: "bed-103-2", code: "G.103-2", status: "available" },
      { id: "bed-103-3", code: "G.103-3", status: "occupied" },
      { id: "bed-103-4", code: "G.103-4", status: "occupied" },
      { id: "bed-103-5", code: "G.103-5", status: "occupied" },
      { id: "bed-103-6", code: "G.103-6", status: "available" },
    ],
    assets: [
      { id: "ast-103-1", name: "Giường tầng", quantity: 3, condition: "Tốt" },
      { id: "ast-103-2", name: "Bàn học", quantity: 6, condition: "Tốt" },
      { id: "ast-103-3", name: "Ghế xoay", quantity: 6, condition: "Tốt" },
      { id: "ast-103-4", name: "Tủ quần áo", quantity: 3, condition: "Cũ" },
      { id: "ast-103-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
    ],
    status: "partially_available",
  },
  {
    id: "room-10",
    code: "P.201",
    area: "Tầng 2",
    type: "2 người",
    maxCapacity: 2,
    basePrice: 5200000,
    beds: [
      { id: "bed-201-1", code: "G.201-1", status: "available" },
      { id: "bed-201-2", code: "G.201-2", status: "available" },
    ],
    assets: [
      { id: "ast-201-1", name: "Giường đơn", quantity: 2, condition: "Mới" },
      { id: "ast-201-2", name: "Bàn học", quantity: 2, condition: "Mới" },
      { id: "ast-201-3", name: "Ghế xoay", quantity: 2, condition: "Mới" },
      { id: "ast-201-4", name: "Tủ quần áo", quantity: 2, condition: "Mới" },
      { id: "ast-201-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-201-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
      { id: "ast-201-7", name: "Tủ lạnh", quantity: 1, condition: "Tốt" },
    ],
    status: "available",
  },
  {
    id: "room-11",
    code: "P.205",
    area: "Tầng 2",
    type: "6 người",
    maxCapacity: 6,
    basePrice: 3400000,
    beds: [
      { id: "bed-205-1", code: "G.205-1", status: "occupied" },
      { id: "bed-205-2", code: "G.205-2", status: "occupied" },
      { id: "bed-205-3", code: "G.205-3", status: "occupied" },
      { id: "bed-205-4", code: "G.205-4", status: "occupied" },
      { id: "bed-205-5", code: "G.205-5", status: "occupied" },
      { id: "bed-205-6", code: "G.205-6", status: "occupied" },
    ],
    assets: [
      { id: "ast-205-1", name: "Giường tầng", quantity: 3, condition: "Cũ" },
      { id: "ast-205-2", name: "Bàn học", quantity: 6, condition: "Cũ" },
      { id: "ast-205-3", name: "Ghế xoay", quantity: 6, condition: "Cũ" },
      { id: "ast-205-4", name: "Tủ quần áo", quantity: 3, condition: "Cũ" },
      { id: "ast-205-5", name: "Điều hòa", quantity: 1, condition: "Cần bảo trì" },
    ],
    status: "full",
  },
  {
    id: "room-12",
    code: "P.206",
    area: "Tầng 2",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 3900000,
    beds: [
      { id: "bed-206-1", code: "G.206-1", status: "maintenance" },
      { id: "bed-206-2", code: "G.206-2", status: "maintenance" },
      { id: "bed-206-3", code: "G.206-3", status: "maintenance" },
      { id: "bed-206-4", code: "G.206-4", status: "maintenance" },
    ],
    assets: [
      { id: "ast-206-1", name: "Giường tầng", quantity: 2, condition: "Hỏng" },
      { id: "ast-206-2", name: "Bàn học", quantity: 4, condition: "Hỏng" },
      { id: "ast-206-3", name: "Ghế xoay", quantity: 4, condition: "Hỏng" },
      { id: "ast-206-4", name: "Tủ quần áo", quantity: 2, condition: "Hỏng" },
      { id: "ast-206-5", name: "Điều hòa", quantity: 1, condition: "Hỏng" },
    ],
    status: "maintenance",
  },
  {
    id: "room-13",
    code: "P.301",
    area: "Tầng 3",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 4400000,
    beds: [
      { id: "bed-301-1", code: "G.301-1", status: "available" },
      { id: "bed-301-2", code: "G.301-2", status: "available" },
      { id: "bed-301-3", code: "G.301-3", status: "available" },
      { id: "bed-301-4", code: "G.301-4", status: "available" },
    ],
    assets: [
      { id: "ast-301-1", name: "Giường tầng", quantity: 2, condition: "Tốt" },
      { id: "ast-301-2", name: "Bàn học", quantity: 4, condition: "Tốt" },
      { id: "ast-301-3", name: "Ghế xoay", quantity: 4, condition: "Tốt" },
      { id: "ast-301-4", name: "Tủ quần áo", quantity: 2, condition: "Tốt" },
      { id: "ast-301-5", name: "Điều hòa", quantity: 1, condition: "Mới" },
      { id: "ast-301-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
      { id: "ast-301-7", name: "Ban công", quantity: 1, condition: "Tốt" },
    ],
    status: "available",
  },
  {
    id: "room-14",
    code: "P.308",
    area: "Tầng 3",
    type: "2 người",
    maxCapacity: 2,
    basePrice: 5300000,
    beds: [
      { id: "bed-308-1", code: "G.308-1", status: "occupied" },
      { id: "bed-308-2", code: "G.308-2", status: "occupied" },
    ],
    assets: [
      { id: "ast-308-1", name: "Giường đơn", quantity: 2, condition: "Tốt" },
      { id: "ast-308-2", name: "Bàn học", quantity: 2, condition: "Tốt" },
      { id: "ast-308-3", name: "Ghế xoay", quantity: 2, condition: "Tốt" },
      { id: "ast-308-4", name: "Tủ quần áo", quantity: 2, condition: "Tốt" },
      { id: "ast-308-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-308-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
      { id: "ast-308-7", name: "Tủ lạnh", quantity: 1, condition: "Tốt" },
    ],
    status: "full",
  },
  {
    id: "room-15",
    code: "P.309",
    area: "Tầng 3",
    type: "6 người",
    maxCapacity: 6,
    basePrice: 4600000,
    beds: [
      { id: "bed-309-1", code: "G.309-1", status: "deposited" },
      { id: "bed-309-2", code: "G.309-2", status: "available" },
      { id: "bed-309-3", code: "G.309-3", status: "available" },
      { id: "bed-309-4", code: "G.309-4", status: "available" },
      { id: "bed-309-5", code: "G.309-5", status: "maintenance" },
      { id: "bed-309-6", code: "G.309-6", status: "maintenance" },
    ],
    assets: [
      { id: "ast-309-1", name: "Giường tầng", quantity: 3, condition: "Tốt" },
      { id: "ast-309-2", name: "Bàn học", quantity: 6, condition: "Tốt" },
      { id: "ast-309-3", name: "Ghế xoay", quantity: 6, condition: "Tốt" },
      { id: "ast-309-4", name: "Tủ quần áo", quantity: 3, condition: "Tốt" },
      { id: "ast-309-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-309-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
      { id: "ast-309-7", name: "Ban công", quantity: 1, condition: "Tốt" },
    ],
    status: "partially_available",
  },
  {
    id: "room-16",
    code: "P.402",
    area: "Tầng 4",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 4800000,
    beds: [
      { id: "bed-402-1", code: "G.402-1", status: "available" },
      { id: "bed-402-2", code: "G.402-2", status: "available" },
      { id: "bed-402-3", code: "G.402-3", status: "available" },
      { id: "bed-402-4", code: "G.402-4", status: "available" },
    ],
    assets: [
      { id: "ast-402-1", name: "Giường tầng", quantity: 2, condition: "Mới" },
      { id: "ast-402-2", name: "Bàn học", quantity: 4, condition: "Mới" },
      { id: "ast-402-3", name: "Ghế xoay", quantity: 4, condition: "Mới" },
      { id: "ast-402-4", name: "Tủ quần áo", quantity: 2, condition: "Mới" },
      { id: "ast-402-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-402-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
      { id: "ast-402-7", name: "Ban công", quantity: 1, condition: "Tốt" },
    ],
    status: "available",
  },
  {
    id: "room-17",
    code: "P.408",
    area: "Tầng 4",
    type: "4 người",
    maxCapacity: 4,
    basePrice: 4900000,
    beds: [
      { id: "bed-408-1", code: "G.408-1", status: "occupied" },
      { id: "bed-408-2", code: "G.408-2", status: "occupied" },
      { id: "bed-408-3", code: "G.408-3", status: "occupied" },
      { id: "bed-408-4", code: "G.408-4", status: "occupied" },
    ],
    assets: [
      { id: "ast-408-1", name: "Giường tầng", quantity: 2, condition: "Tốt" },
      { id: "ast-408-2", name: "Bàn học", quantity: 4, condition: "Tốt" },
      { id: "ast-408-3", name: "Ghế xoay", quantity: 4, condition: "Tốt" },
      { id: "ast-408-4", name: "Tủ quần áo", quantity: 2, condition: "Tốt" },
      { id: "ast-408-5", name: "Điều hòa", quantity: 1, condition: "Tốt" },
      { id: "ast-408-6", name: "Máy nước nóng", quantity: 1, condition: "Tốt" },
    ],
    status: "full",
  },
  {
    id: "room-18",
    code: "P.409",
    area: "Tầng 4",
    type: "6 người",
    maxCapacity: 6,
    basePrice: 5100000,
    beds: [
      { id: "bed-409-1", code: "G.409-1", status: "maintenance" },
      { id: "bed-409-2", code: "G.409-2", status: "maintenance" },
      { id: "bed-409-3", code: "G.409-3", status: "maintenance" },
      { id: "bed-409-4", code: "G.409-4", status: "maintenance" },
      { id: "bed-409-5", code: "G.409-5", status: "maintenance" },
      { id: "bed-409-6", code: "G.409-6", status: "maintenance" },
    ],
    assets: [
      { id: "ast-409-1", name: "Giường tầng", quantity: 3, condition: "Cần bảo trì" },
      { id: "ast-409-2", name: "Bàn học", quantity: 6, condition: "Cần bảo trì" },
      { id: "ast-409-3", name: "Ghế xoay", quantity: 6, condition: "Cần bảo trì" },
      { id: "ast-409-4", name: "Tủ quần áo", quantity: 3, condition: "Cần bảo trì" },
    ],
    status: "maintenance",
  },
];

export const roomAreas = ["Tầng 1", "Tầng 2", "Tầng 3", "Tầng 4"];
export const roomTypes = ["2 người", "4 người", "6 người"];
