@startuml
title Đăng nhập
skinparam responseMessageBelowArrow true

boundary MHDangNhap
control XacThucNguoiDung
control TaiKhoan
entity TaiKhoanDB

MHDangNhap -> XacThucNguoiDung: DangNhap()
XacThucNguoiDung -> TaiKhoan: DocTheoTenDangNhap()
TaiKhoan -> TaiKhoanDB: DocTheoTenDangNhap()
XacThucNguoiDung -> TaiKhoan: DangHoatDong()
XacThucNguoiDung -> TaiKhoan: KiemTraMatKhau()
TaiKhoan -> TaiKhoanDB: CapNhatLanDangNhap()
@enduml
