@startuml
title Đăng nhập

actor "Nguoi dung" as ND

box "GUI" #D5F5D3
boundary MHDangNhap
end box

box "BUS" #FCF3CF
control XacThucNguoiDung
control TaiKhoan
end box

box "DB" #D6EAF8
entity TaiKhoanDB
end box
skinparam responseMessageBelowArrow true


ND -> MHDangNhap : Nhap ten dang nhap va mat khau
ND -> MHDangNhap : Nhan "Dang nhap"
activate MHDangNhap
MHDangNhap -> MHDangNhap : btnDangNhap_Click()
MHDangNhap -> XacThucNguoiDung: DangNhap(tenDangNhap, matKhau)
activate XacThucNguoiDung
XacThucNguoiDung -> TaiKhoan: DocTheoTenDangNhap(tenDangNhap)
activate TaiKhoan
TaiKhoan -> TaiKhoanDB: DocTheoTenDangNhap(tenDangNhap)
activate TaiKhoanDB
deactivate TaiKhoanDB
deactivate TaiKhoan
XacThucNguoiDung -> TaiKhoan: DangHoatDong()
activate TaiKhoan
deactivate TaiKhoan
XacThucNguoiDung -> TaiKhoan: KiemTraMatKhau(matKhau)
activate TaiKhoan
deactivate TaiKhoan
XacThucNguoiDung -> TaiKhoan: CapNhatLanDangNhap()
activate TaiKhoan
TaiKhoan -> TaiKhoanDB: CapNhatLanDangNhap()
activate TaiKhoanDB
deactivate TaiKhoanDB
deactivate TaiKhoan
deactivate XacThucNguoiDung
deactivate MHDangNhap
@enduml
