@startuml
title SO DO TUAN TU - HUY PHIEU COC
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Nhan vien Sale" as Sale
box "GUI" #D5F5D3
boundary ": MHHuyPhieuCoc" as MH
end box
box "BUS" #FCF3CF
control ": TraCuuPhieuCoc" as TC
control ": HuyPhieuCoc" as UC
control ": NhanVien" as NV
control ": HopDong" as HD
control ": PhieuCoc" as PC
control ": Phong" as P
control ": Giuong" as G
end box
box "DB" #D6EAF8
entity ": NhanVienDB" as NVDB
entity ": HopDongDB" as HDDB
entity ": PhieuCocDB" as PCDB
entity ": PhongDB" as PDB
end box

Sale -> MH : Chon chuc nang "Huy phieu coc"
activate MH
MH -> MH : HienThi()
MH -> MH : taiDanhSachCoTheHuy(text)
MH -> TC : LayDanhSachCoTheHuy(text, maNV)
activate TC
TC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
TC -> PC : LayDanhSachCoTheHuy(maCN, text)
activate PC
PC -> PCDB : LayDanhSachCoTheHuy(maCN, text)
activate PCDB
deactivate PCDB
deactivate PC
deactivate TC
Sale -> MH : Chon phieu coc can huy
MH -> MH : chonPhieuCoc(maPhieuCoc)
MH -> TC : LayChiTiet(maPhieuCoc, maNV)
activate TC
TC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
TC -> PC : DocChiTiet(maPhieuCoc, maCN)
activate PC
PC -> PCDB : DocChiTiet(maPhieuCoc, maCN)
activate PCDB
deactivate PCDB
deactivate PC
deactivate TC
Sale -> MH : Nhan "Huy dat coc"
MH -> MH : moHopThoaiXacNhan()
Sale -> MH : Xac nhan huy phieu coc
MH -> MH : huyPhieuCoc()
MH -> UC : Huy(maPhieuCoc, maNhanVien)
activate UC
UC -> NV : DocPhamVi(maNhanVien)
activate NV
NV -> NVDB : DocChiTiet(maNhanVien)
activate NVDB
deactivate NVDB
deactivate NV
UC -> PC : DocChiTietChoCapNhat(maPhieuCoc, maCN)
activate PC
PC -> PCDB : DocChiTietChoCapNhat(maPhieuCoc, maCN)
activate PCDB
deactivate PCDB
deactivate PC
UC -> HD : TonTaiTheoPhieuCoc(maPhieuCoc)
activate HD
HD -> HDDB : TonTaiTheoPhieuCoc(maPhieuCoc)
activate HDDB
deactivate HDDB
deactivate HD
UC -> P : DocChiTiet(maPhong)
activate P
P -> PDB : DocChiTiet(maPhong)
activate PDB
deactivate PDB
deactivate P
UC -> PC : Huy(maNhanVien, thoiDiem)
activate PC
deactivate PC
UC -> P : GiaiPhongDatCoc(maGiuongs)
activate P
loop Moi giuong cua phieu coc
  P -> G : GiaiPhong(maPhong)
  activate G
  deactivate G
end
deactivate P
UC -> PC : CapNhatHuy()
activate PC
PC -> PCDB : CapNhatHuy(phieuCoc)
activate PCDB
deactivate PCDB
deactivate PC
UC -> P : CapNhatGiaiPhongDatCoc()
activate P
P -> PDB : CapNhatGiaiPhongDatCoc(phong)
activate PDB
deactivate PDB
deactivate P
deactivate UC
deactivate MH
@enduml
