@startuml
title SO DO TUAN TU - HUY PHIEU COC
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Nhan vien Sale" as NV
actor "He thong" as HT
boundary ": MHHuyPhieuCoc" as MH
control ": HuyPhieuCoc" as HC
control ": HopDong" as HD
entity ": HopDongDB" as HDDB
control ": PhieuCoc" as PC
entity ": PhieuCocDB" as PCDB
control ": Phong" as P
entity ": PhongDB" as PDB
control ": DichVuThongBao" as DV
control ": ThongBao" as TB
entity ": ThongBaoDB" as TBDB

NV -> MH : chon phieu va xac nhan huy
MH -> HC : Huy(maPhieuCoc, maNhanVien)
HC -> PC : DocChiTiet(maPhieuCoc)
PC -> PCDB : DocChiTiet(maPhieuCoc)
HC -> HD : TonTaiTheoPhieuCoc(maPhieuCoc)
HD -> HDDB : TonTaiTheoPhieuCoc(maPhieuCoc)
HC -> P : DocChiTiet(maPhong)
P -> PDB : DocChiTiet(maPhong)
HC -> PC : Huy(maNhanVien, thoiDiem)
HC -> P : GiaiPhongDatCoc(maGiuongs)
HC -> PC : CapNhatHuy()
PC -> PCDB : CapNhatHuy(phieu)
HC -> P : CapNhatGiaiPhongDatCoc()
P -> PDB : CapNhatGiaiPhongDatCoc(phong)
alt phieu.DaDongTien
  HC -> DV : GuiThongBaoKeToan(tieuDe, noiDung, lienKet, maNhanVien, maPhieuCoc)
  DV -> TB : Tao(tieuDe, noiDung, KeToan, lienKet, orange, maNhanVien, maPhieuCoc, thoiDiem)
  DV -> TB : Luu()
  TB -> TBDB : Them(thongBao)
end

== Tu dong huy phieu qua han ==
HT -> HC : LayDanhSachMaQuaHan(thoiDiemHienTai, batchSize)
HC -> PC : LayDanhSachMaQuaHan(thoiDiemHienTai, batchSize)
PC -> PCDB : LayDanhSachMaQuaHan(thoiDiemHienTai, batchSize)
loop tung ma phieu coc qua han
  HT -> HC : TuDongHuyQuaHan(maPhieuCoc, thoiDiemHienTai)
  HC -> PC : DocChiTietChoCapNhat(maPhieuCoc)
  PC -> PCDB : DocChiTietChoCapNhat(maPhieuCoc)
  HC -> PC : CoTheTuDongHuy(thoiDiemHienTai)
  HC -> HD : TonTaiTheoPhieuCoc(maPhieuCoc)
  HD -> HDDB : TonTaiTheoPhieuCoc(maPhieuCoc)
  HC -> P : DocChiTiet(maPhong)
  P -> PDB : DocChiTiet(maPhong)
  HC -> PC : TuDongHuyQuaHan(thoiDiemHienTai)
  HC -> P : GiaiPhongDatCoc(maGiuongs)
  HC -> PC : CapNhatTuDongHuy(thoiDiemHienTai)
  PC -> PCDB : CapNhatTuDongHuy(phieu, thoiDiemHienTai)
  HC -> P : CapNhatGiaiPhongDatCoc()
  P -> PDB : CapNhatGiaiPhongDatCoc(phong)
  HC -> DV : GuiThongBaoSale(tieuDe, noiDung, lienKet, maNVGui, maPhieuCoc)
  DV -> TB : Tao(tieuDe, noiDung, Sale, lienKet, orange, maNVGui, maPhieuCoc, thoiDiem)
  DV -> TB : Luu()
  TB -> TBDB : Them(thongBao)
end
@enduml
