@startuml
title SO DO TUAN TU - LAP PHIEU COC

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Nhan vien kinh doanh" as Sale

box "GUI" #D5F5D3
boundary ": MHLapPhieuCoc" as MH
end box

box "BUS" #FCF3CF
control ": LapPhieuCoc" as LPC
control ": NhanVien" as NV
control ": LichHen" as LH
control ": KhachHang" as KH
control ": Phong" as P
control ": Giuong" as G
control ": PhieuCoc" as PC
end box

box "DB" #D6EAF8
entity ": NhanVienDB" as NVDB
entity ": LichHenDB" as LHDB
entity ": KhachHangDB" as KHDB
entity ": PhongDB" as PDB
entity ": PhieuCocDB" as PCDB
end box

Sale -> MH : Chon chuc nang "Lap phieu coc"
activate MH
MH -> MH : HienThi()
MH -> LPC : LayDanhSachKhachChoCoc(maNV)
activate LPC
LPC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
LPC -> LH : LayDanhSachKhachChoCoc(maCN)
activate LH
LH -> LHDB : LayDanhSachKhachChoCoc(maCN)
activate LHDB
deactivate LHDB
deactivate LH
deactivate LPC

opt Sale nhap tu khoa tim lich hen
  Sale -> MH : Nhap ma lich, ten khach hoac so dien thoai
  MH -> MH : timKiemLichHen(text)
  MH -> LPC : TimKiemKhachChoCoc(text, maNV)
  activate LPC
  LPC -> NV : DocPhamVi(maNV)
  activate NV
  NV -> NVDB : DocChiTiet(maNV)
  activate NVDB
  deactivate NVDB
  deactivate NV
  LPC -> LH : LayDanhSachKhachChoCoc(maCN, text)
  activate LH
  LH -> LHDB : LayDanhSachKhachChoCoc(maCN, text)
  activate LHDB
  deactivate LHDB
  deactivate LH
  deactivate LPC
end

Sale -> MH : Chon mot lich hen da xem phong
MH -> MH : chonLichHen(lichHen)
MH -> LPC : LayChiTietLichHen(maLichHen, maNV)
activate LPC
LPC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
LPC -> LH : DocChiTiet(maLichHen, maCN, false)
activate LH
LH -> LHDB : DocChiTiet(maLichHen, maCN, false)
activate LHDB
deactivate LHDB
deactivate LH
deactivate LPC

opt Khach hang thay doi thong tin
  Sale -> MH : Nhan "Chinh sua" va cap nhat thong tin
end

Sale -> MH : Chon hinh thuc thue
MH -> MH : chonHinhThucThue(hinhThucThue)
opt HinhThucThue = OGhep
  Sale -> MH : Nhap so luong giuong can coc
end
Sale -> MH : Chon bo loc phong
Sale -> MH : Nhan "Tim phong"
MH -> MH : timPhong()

alt HinhThucThue = NguyenCan
  MH -> LPC : LayPhongNguyenCan(toaNha, loaiPhong, giaMin, giaMax, gioiTinh, maNV)
  activate LPC
  LPC -> NV : DocPhamVi(maNV)
  activate NV
  NV -> NVDB : DocChiTiet(maNV)
  activate NVDB
  deactivate NVDB
  deactivate NV
  LPC -> P : LayPhongNguyenCan(toaNha, loaiPhong, giaMin, giaMax, maCN, gioiTinh)
  activate P
  P -> PDB : LayPhongNguyenCan(toaNha, loaiPhong, giaMin, giaMax, maCN, gioiTinh)
  activate PDB
  deactivate PDB
  deactivate P
  deactivate LPC
else HinhThucThue = OGhep
  MH -> LPC : LayPhongOGhep(soLuong, toaNha, loaiPhong, giaMin, giaMax, gioiTinh, maNV)
  activate LPC
  LPC -> NV : DocPhamVi(maNV)
  activate NV
  NV -> NVDB : DocChiTiet(maNV)
  activate NVDB
  deactivate NVDB
  deactivate NV
  LPC -> P : LayPhongOGhep(soLuong, toaNha, loaiPhong, giaMin, giaMax, maCN, gioiTinh)
  activate P
  P -> PDB : LayPhongOGhep(soLuong, toaNha, loaiPhong, giaMin, giaMax, maCN, gioiTinh)
  activate PDB
  deactivate PDB
  deactivate P
  deactivate LPC
end

alt HinhThucThue = NguyenCan
  Sale -> MH : Chon mot phong trong
  MH -> MH : chonNguyenPhong(phong)
else HinhThucThue = OGhep
  Sale -> MH : Chon hoac bo chon tung giuong
  MH -> MH : chonBoChonGiuong(phong, maGiuong)
end

Sale -> MH : Nhan "Tao phieu va gui Ke toan"
MH -> MH : moHopThoaiXacNhan()
Sale -> MH : Xac nhan tao phieu coc
MH -> MH : taoPhieuCoc()
MH -> LPC : TaoPhieuCoc(maLichHen, thongTinKhachHang, maPhong, danhSachGiuong, hinhThucThue, maNV)
activate LPC

LPC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
LPC -> LH : DocChiTiet(maLichHen, maCN, true)
activate LH
LH -> LHDB : DocChiTiet(maLichHen, maCN, true)
activate LHDB
deactivate LHDB
LH -> LH : KiemTraCoTheLapPhieuCoc()
deactivate LH

LPC -> LPC : KiemTraThongTinKhachHang(thongTinKhachHang)
LPC -> KH : CapNhatTu(thongTinKhachHang)
activate KH
deactivate KH
opt Thong tin khach hang da thay doi
  LPC -> KH : CapNhat()
  activate KH
  KH -> KHDB : CapNhat(khachHang)
  activate KHDB
  deactivate KHDB
  deactivate KH
end

LPC -> P : DocChiTiet(maPhong, maCN)
activate P
P -> PDB : DocChiTiet(maPhong, maCN)
activate PDB
deactivate PDB
P -> P : KiemTraGioiTinhChoPhep(dsKhach)
alt HinhThucThue = NguyenCan
  P -> P : GiuNguyenPhong()
  loop Moi giuong trong phong
    P -> G : GiuCho(maPhong)
    activate G
    deactivate G
  end
else HinhThucThue = OGhep
  P -> P : GiuGiuong(danhSachGiuong)
  loop Moi giuong da chon
    P -> G : GiuCho(maPhong)
    activate G
    deactivate G
  end
end
deactivate P

LPC -> PC : TaoMoi(hinhThucThue, khachHang, phong, giuongs, maNV, thoiDiemCoc)
activate PC
deactivate PC
LPC -> PC : Them()
activate PC
PC -> PCDB : Them(phieuCoc)
activate PCDB
deactivate PCDB
deactivate PC

LPC -> LH : GanPhieuCoc(maPhieuCoc)
activate LH
deactivate LH
LPC -> P : CapNhat()
activate P
P -> PDB : CapNhat(phong)
activate PDB
deactivate PDB
deactivate P
LPC -> LH : LuuPhieuCoc()
activate LH
LH -> LHDB : GanPhieuCoc(lichHen)
activate LHDB
deactivate LHDB
deactivate LH

deactivate LPC
deactivate MH

@enduml
