@startuml
title SO DO TUAN TU - LAP BIEN BAN BAN GIAO

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Quản lý" as QL

box "GUI" #D5F5D3
boundary ": MHLapBienBanBanGiao" as MH
end box

box "BUS" #FCF3CF
control ": LapBienBanBanGiao" as LBB
control ": HopDong" as HD
control ": BienBanGiaoNhan" as BB
control ": ChiTietGiaoNhan" as CT
control ": PhongTaiSan" as PTS
control ": Giuong" as G
end box

box "DB" #D6EAF8
entity ": HopDongDB" as HDDB
entity ": BienBanGiaoNhanDB" as BBDB
entity ": ChiTietGiaoNhanDB" as CTDB
entity ": PhongTaiSanDB" as PTSDB
entity ": GiuongDB" as GDB
end box

'=====================
' TẢI DANH SÁCH HỢP ĐỒNG
'=====================

QL -> MH : Chon chuc nang va mo man hinh
MH -> MH : hienThiForm()
activate MH
MH -> LBB : LayDanhSachChoBanGiao()
activate LBB
LBB -> HD : LayDanhSachChoBanGiao()
activate HD
HD -> HDDB : LayDanhSachChoBanGiao()
activate HDDB
deactivate HDDB
deactivate HD
deactivate LBB

QL -> MH : Nhap thong tin tren giao dien
MH -> MH : nhapTuKhoaTimKiem(tuKhoa)
MH -> LBB : LayDanhSachChoBanGiao(tuKhoa)
activate LBB
LBB -> HD : LayDanhSachChoBanGiao(tuKhoa)
activate HD
HD -> HDDB : LayDanhSachChoBanGiao(tuKhoa)
activate HDDB
deactivate HDDB
deactivate HD
deactivate LBB

'=====================
' CHỌN HỢP ĐỒNG VÀ TẢI TÀI SẢN
'=====================

QL -> MH : Chon doi tuong tren giao dien
MH -> MH : chonHopDong(maHD)
MH -> LBB : LayChiTietBanGiao(maHD)
activate LBB

LBB -> HD : DocChiTiet(maHD)
activate HD
HD -> HDDB : DocChiTiet(maHD)
activate HDDB
deactivate HDDB
deactivate HD

LBB -> HD : KiemTraChoBanGiao()
activate HD
deactivate HD

LBB -> BB : TonTaiBanGiaoTheoHD(maHD)
activate BB
BB -> BBDB : TonTaiBanGiaoTheoHD(maHD)
activate BBDB
deactivate BBDB
deactivate BB

LBB -> PTS : LayTaiSanTheoPhong(maPhong)
activate PTS
PTS -> PTSDB : LayTaiSanTheoPhong(maPhong)
activate PTSDB
deactivate PTSDB
deactivate PTS
deactivate LBB

'=====================
' NHẬP HIỆN TRẠNG VÀ CHỐT
'=====================

QL -> MH : Nhap thong tin tren giao dien
MH -> MH : nhapSoLuongVaTinhTrang()
QL -> MH : Nhan "Chot Ban Giao"
MH -> MH : btnChotBanGiao_Click()

MH -> LBB : ChotBienBan(maHD, maNV, taiSan)
activate LBB

LBB -> HD : DocChiTiet(maHD)
activate HD
HD -> HDDB : DocChiTiet(maHD)
activate HDDB
deactivate HDDB
deactivate HD

LBB -> HD : KiemTraChoBanGiao()
activate HD
deactivate HD

LBB -> BB : TonTaiBanGiaoTheoHD(maHD)
activate BB
BB -> BBDB : TonTaiBanGiaoTheoHD(maHD)
activate BBDB
deactivate BBDB
deactivate BB

LBB -> PTS : LayTaiSanTheoPhong(maPhong)
activate PTS
PTS -> PTSDB : LayTaiSanTheoPhong(maPhong)
activate PTSDB
deactivate PTSDB
deactivate PTS


LBB -> CT : KiemTraHopLe()
activate CT
deactivate CT

LBB -> BB : KhoiTaoBanGiao(maHD, maNV, ngayBanGiao, chiTiet)
activate BB
deactivate BB

LBB -> BB : KiemTraDuLieuTaiSan()
activate BB
deactivate BB

LBB -> BB : LuuBienBan()
activate BB
BB -> BBDB : Them(bienBan)
activate BBDB
deactivate BBDB
deactivate BB

LBB -> CT : ThemNhieu(chiTiet)
activate CT
CT -> CTDB : ThemNhieu(chiTiet)
activate CTDB
deactivate CTDB
deactivate CT

LBB -> G : CapNhatDangSuDungTheoHD(maHD)
activate G
G -> GDB : UpdateTrangThaiTheoHopDong(maHD, "DangSuDung")
activate GDB
deactivate GDB
deactivate G

LBB -> HD : ChuyenTrangThaiDangHieuLuc()
activate HD
HD -> HDDB : UpdateTrangThai(maHD, "DangHieuLuc")
activate HDDB
deactivate HDDB
deactivate HD

deactivate LBB

'=====================
' HỦY BÀN GIAO
'=====================

QL -> MH : Nhan "Huy Ban Giao"
MH -> MH : btnHuyBanGiao_Click()
MH -> MH : hienThiThongBaoHuy()
deactivate MH

@enduml
