@startuml
title SO DO TUAN TU - LAP HOA DON BOI THUONG

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Ke toan" as KT

box "GUI" #D5F5D3
boundary ": MHLapHoaDonBoiThuong" as MH
end box

box "BUS" #FCF3CF
control ": BienBanGiaoNhan" as BB
control ": ChiTietGiaoNhan" as CTGN
control ": TaiSan" as TS
control ": NhanVien" as NV
control ": HoaDon" as HD
control ": ChiTietHoaDon" as CTHD
end box

box "DB" #D6EAF8
entity ": BienBanGiaoNhanDB" as BBDB
entity ": ChiTietGiaoNhanDB" as CTGNDB
entity ": TaiSanDB" as TSDB
entity ": NhanVienDB" as NVDB
entity ": HoaDonDB" as HDDB
entity ": ChiTietHoaDonDB" as CTHDDB
end box

KT -> MH : Mo man hinh lap hoa don boi thuong
activate MH
MH -> MH : taiDanhSach(tuKhoa)
MH -> BB : LayDSBienBanThuHoiChuaXuLy(tuKhoa)
activate BB
BB -> BBDB : GetDSBienBanThuHoiChuaXuLy(tuKhoa)
activate BBDB
deactivate BBDB
deactivate BB

KT -> MH : Chon bien ban thu hoi
MH -> MH : chonBienBan(maBienBan)
MH -> BB : LayChiTietBienBan(maBienBan)
activate BB
BB -> BBDB : GetBienBanTheoMaBienBan(maBienBan)
activate BBDB
deactivate BBDB
deactivate BB
MH -> CTGN : LayDSTaiSanHuHongTheoBienBan(maBienBan)
activate CTGN
CTGN -> CTGNDB : GetDSTaiSanHuHongTheoBienBan(maBienBan)
activate CTGNDB
deactivate CTGNDB
deactivate CTGN
loop Moi tai san hu hong hoac mat mat
  MH -> TS : LayThongTinTaiSan(maTS)
  activate TS
  TS -> TSDB : GetTaiSanTheoMaTS(maTS)
  activate TSDB
  deactivate TSDB
  deactivate TS
end

KT -> MH : Nhap so tien boi thuong cho tung tai san
KT -> MH : Nhan "Lap hoa don"
MH -> MH : lapHoaDon()
MH -> HD : KiemTraTinhHopLe(dsSoTien)
activate HD
deactivate HD
MH -> NV : LayThongTinNhanVien(maNV)
activate NV
NV -> NVDB : GetNhanVienTheoMaNV(maNV)
activate NVDB
deactivate NVDB
deactivate NV
MH -> HD : TaoHoaDonBoiThuong(maBienBan, tongTien, maNV, ngayLap, ghiChu)
activate HD
HD -> BB : LayChiTietBienBan(maBienBan)
activate BB
BB -> BBDB : GetBienBanTheoMaBienBan(maBienBan)
activate BBDB
deactivate BBDB
deactivate BB
HD -> BB : DaCoHoaDonBoiThuongTheoHD(maHD)
activate BB
BB -> BBDB : DaCoHoaDonBoiThuongTheoHD(maHD)
activate BBDB
deactivate BBDB
deactivate BB
HD -> CTGN : LayDSTaiSanHuHongTheoBienBan(maBienBan)
activate CTGN
CTGN -> CTGNDB : GetDSTaiSanHuHongTheoBienBan(maBienBan)
activate CTGNDB
deactivate CTGNDB
deactivate CTGN
HD -> HDDB : InsertHoaDon(hoaDon)
activate HDDB
deactivate HDDB
deactivate HD
MH -> CTHD : TaoChiTietHoaDon(maHoaDon, dsChiTiet)
activate CTHD
loop Moi dong boi thuong
  CTHD -> CTHDDB : InsertChiTietHoaDon(chiTiet)
  activate CTHDDB
  deactivate CTHDDB
end
deactivate CTHD

deactivate MH
@enduml
