@startuml
title SO DO TUAN TU - LAP BIEN BAN THU HOI TAI SAN
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Quan ly" as QL
box "GUI" #D5F5D3
boundary ": MHLapBienBanThuHoiTaiSan" as MH
end box
box "BUS" #FCF3CF
control ": LapBienBanThuHoiTaiSan" as UC
control ": HopDong" as HD
control ": PhongTaiSan" as PTS
control ": BienBanGiaoNhan" as BB
control ": ChiTietGiaoNhan" as CT
end box
box "DB" #D6EAF8
entity ": HopDongDB" as HDDB
entity ": PhongTaiSanDB" as PTSDB
entity ": BienBanGiaoNhanDB" as BBDB
entity ": ChiTietGiaoNhanDB" as CTDB
end box

QL -> MH : Chon chuc nang "Thu hoi tai san"
activate MH
MH -> MH : HienThi()
MH -> UC : LayDanhSachHopDongTraPhongHomNay(tuKhoa)
activate UC
UC -> HD : LayDanhSachCoLichTraTrongNgay(tuKhoa)
activate HD
HD -> HDDB : LayDanhSachCoLichTraTrongNgay(tuKhoa)
activate HDDB
deactivate HDDB
deactivate HD
deactivate UC
QL -> MH : Chon hop dong tra phong
MH -> MH : chonHopDong(maHD)
MH -> UC : LayChiTietHopDongThuHoi(maHD)
activate UC
UC -> HD : DocChiTiet(maHD)
activate HD
HD -> HDDB : DocChiTiet(maHD)
activate HDDB
deactivate HDDB
HD -> HD : KiemTraDangHieuLuc()
deactivate HD
UC -> HD : CoLichTraPhongTrongNgay(maHD)
activate HD
HD -> HDDB : CoLichTraPhongTrongNgay(maHD)
activate HDDB
deactivate HDDB
deactivate HD
UC -> BB : TonTaiThuHoiTheoHD(maHD)
activate BB
BB -> BBDB : TonTaiThuHoiTheoHD(maHD)
activate BBDB
deactivate BBDB
deactivate BB
UC -> PTS : LayTaiSanTheoPhong(maPhong)
activate PTS
PTS -> PTSDB : LayTaiSanTheoPhong(maPhong)
activate PTSDB
deactivate PTSDB
deactivate PTS
deactivate UC

QL -> MH : Nhap so luong va tinh trang tai san
MH -> MH : capNhatTaiSan(maTS, soLuong, tinhTrang)
QL -> MH : Nhan "Luu bien ban"
MH -> MH : lapBienBan()
MH -> UC : LapBienBan(maHD, maNV, taiSan)
activate UC
UC -> HD : DocChiTiet(maHD)
activate HD
HD -> HDDB : DocChiTiet(maHD)
activate HDDB
deactivate HDDB
HD -> HD : KiemTraDangHieuLuc()
deactivate HD
UC -> BB : TonTaiThuHoiTheoHD(maHD)
activate BB
BB -> BBDB : TonTaiThuHoiTheoHD(maHD)
activate BBDB
deactivate BBDB
deactivate BB
UC -> PTS : LayTaiSanTheoPhong(maPhong)
activate PTS
PTS -> PTSDB : LayTaiSanTheoPhong(maPhong)
activate PTSDB
deactivate PTSDB
deactivate PTS
loop Moi tai san thu hoi
  UC -> CT : KiemTraHopLe()
  activate CT
  deactivate CT
end
UC -> BB : KhoiTaoThuHoi(maHD, maNV, ngayBanGiao, chiTiet)
activate BB
BB -> BB : KiemTraDuLieuTaiSan()
deactivate BB
UC -> BB : LuuBienBan()
activate BB
BB -> BBDB : Them(bienBan)
activate BBDB
deactivate BBDB
deactivate BB
UC -> CT : ThemNhieu(chiTiet)
activate CT
CT -> CTDB : ThemNhieu(chiTiet)
activate CTDB
deactivate CTDB
deactivate CT
deactivate UC
deactivate MH
@enduml
