@startuml LapBienBanThuHoiTaiSan_3Lop

skinparam classAttributeIconSize 0
skinparam classFontSize 12
skinparam classHeaderBackgroundColor #AED6F1
skinparam classBorderColor #2980B9
skinparam classBackgroundColor #EBF5FB
skinparam ArrowColor #2C3E50
skinparam ArrowThickness 1.5
skinparam shadowing false
skinparam roundcorner 6
skinparam linetype ortho


'=====================
' LỚP GIAO DIỆN
'=====================

package "Lớp giao diện" #EBF5FB {

class MHLapBienBanThuHoi {

+txtTimKiem : TextBox
+grvDSHopDongTraPhong : DataGridView
+lblThongTinHopDong : Label
+grvTaiSanThuHoi : DataGridView
+txtSoLuongThuHoi : TextBox
+cbTinhTrang : ComboBox
+uplMinhChung : FileUpload
+txtGhiChu : TextBox
+btnLuuBienBan : Button

'---
+hienThiForm()
+nhapTuKhoaTimKiem()
+hienThiDanhSachHopDong()
+chonHopDong()
+hienThiDanhSachTaiSan()
+nhapSoLuongTinhTrangMinhChung()
+btnLuuBienBan_Click()
+hienThiThongBaoThanhCong()
+hienThiLoiDuLieu()

}

}


'=====================
' LỚP NGHIỆP VỤ
'=====================

package "Lớp nghiệp vụ" #FEF9E7 {

class DieuKhienLapBienBanThuHoi {

+maNVDangNhap : String

'---
+khoiTaoForm()
+timKiemHopDongTraPhongTrongNgay()
+layChiTietHopDongThuHoi()
+luuBienBanThuHoi()

}


class HopDong {

+maHD : String
+trangThai : String

'---
+layDanhSachCoLichTraTrongNgay()
+timKiem()
+layThongTinChiTiet()
+kiemTraDangHieuLuc()

}


class LichHen {

+maLH : String
+ngayHen : Date
+loaiLichHen : String
+trangThai : String
+maHD : String

'---
+layLichTraPhongTrongNgay()

}


class BienBanGiaoNhan {

+maBienBan : String
+ngayBanGiao : DateTime
+loaiBienBan : String
+maHD : String
+maNV : String

'---
+khoiTaoThuHoi()
+kiemTraDuLieuTaiSan()
+luuBienBan()

}


class ChiTietGiaoNhan {

+maBienBan : String
+maTS : String
+tinhTrang : String
+soLuong : int
+ghiChu : String
+minhChung : String

'---
+napDanhSachTaiSan()
+capNhatThuHoi()
+kiemTraHopLe()
+luuChiTiet()

}


class DichVuThongBao {

'---
+guiThongBaoKeToan()

}

}


'=====================
' LỚP TRUY XUẤT DỮ LIỆU
'=====================

package "Lớp truy xuất dữ liệu" #FDF2F8 {

class HopDongDB {

+getDanhSachCoLichTraTrongNgay()
+search()
+getChiTiet()
+checkTrangThai()

}

class LichHenDB {

+getLichTraPhongTrongNgay()

}

class BienBanGiaoNhanDB {

+insertBienBan()

}

class ChiTietGiaoNhanDB {

+getTaiSanTheoPhong()
+insertChiTiet()

}

class NhanVienDB {

+getNhanVien()

}

}


'=====================
' QUAN HỆ
'=====================

MHLapBienBanThuHoi o-- DieuKhienLapBienBanThuHoi

DieuKhienLapBienBanThuHoi o-- HopDong
DieuKhienLapBienBanThuHoi o-- LichHen
DieuKhienLapBienBanThuHoi o-- BienBanGiaoNhan
DieuKhienLapBienBanThuHoi o-- ChiTietGiaoNhan
DieuKhienLapBienBanThuHoi o-- DichVuThongBao
DieuKhienLapBienBanThuHoi o-- NhanVienDB

HopDong o-- HopDongDB
LichHen o-- LichHenDB
BienBanGiaoNhan o-- BienBanGiaoNhanDB
ChiTietGiaoNhan o-- ChiTietGiaoNhanDB

@enduml