@startuml
title SO DO TUAN TU - LAP PHIEU DOI SOAT
hide footbox
autonumber 1 1
skinparam shadowing false

actor "Ke toan" as KT

box "GUI" #D5F5D3
boundary ": MHLapPhieuDoiSoat" as MH
end box

box "BUS" #FCF3CF
control ": LapPhieuDoiSoat" as LPDS
control ": PhieuCoc" as PC
control ": PhieuThu" as PT
control ": HopDong" as HD
control ": ChinhSachHoanCoc" as CS
control ": HoaDon" as HDON
control ": PhieuDoiSoat" as PDS
control ": DichVuThongBao" as TB
end box

box "DB" #D6EAF8
entity ": PhieuCocDB" as PCDB
entity ": PhieuThuDB" as PTDB
entity ": HopDongDB" as HDDB
entity ": ChinhSachHoanCocDB" as CSDB
entity ": HoaDonDB" as HDONDB
entity ": PhieuDoiSoatDB" as PDSDB
end box

KT -> MH : mo man hinh doi soat
activate MH
MH -> MH : loadHoSoList(text)
MH -> LPDS : LayDanhSachChoDoiSoat(text)
activate LPDS
LPDS -> HD : LayDanhSachChoDoiSoat()
activate HD
HD -> HDDB : LayDanhSachChoDoiSoat()
activate HDDB
deactivate HDDB
deactivate HD
LPDS -> PC : LayDanhSachDaHuyChoDoiSoat()
activate PC
PC -> PCDB : LayDanhSachDaHuyChoDoiSoat()
activate PCDB

deactivate PCDB
deactivate PC
deactivate LPDS
KT -> MH : chon ho so
MH -> MH : loadDetail()
MH -> LPDS : LayChiTietVaTinhToan(maHoSo, loaiHoSo)
activate LPDS
alt loaiHoSo = PhieuCoc
  LPDS -> PC : DocChiTiet(maHoSo)
  activate PC
  PC -> PCDB : DocChiTiet(maHoSo)
  activate PCDB
deactivate PCDB
deactivate PC
  LPDS -> PC : KiemTraCoTheDoiSoatHoanCoc()
  activate PC
deactivate PC
  LPDS -> HD : TonTaiTheoPhieuCoc(maHoSo)
  activate HD
  HD -> HDDB : TonTaiTheoPhieuCoc(maHoSo)
  activate HDDB
deactivate HDDB
deactivate HD
  LPDS -> PT : LayTheoPhieuCoc(maHoSo)
  activate PT
  PT -> PTDB : LayTheoPhieuCoc(maHoSo)
  activate PTDB
deactivate PTDB
deactivate PT
  LPDS -> PT : KiemTraKhopTienCoc(phieuCoc)
  activate PT
deactivate PT
  LPDS -> PDS : TonTaiChoPhieuCocChuaKy(maHoSo)
  activate PDS
  PDS -> PDSDB : TonTaiChoPhieuCocChuaKy(maHoSo)
  activate PDSDB
deactivate PDSDB
deactivate PDS
  LPDS -> CS : LayChinhSachDangApDung(homNay)
  activate CS
  CS -> CSDB : LayChinhSachDangApDung(homNay)
  activate CSDB
deactivate CSDB
deactivate CS
  LPDS -> PDS : TaoMoi(maHoSo, null, null, thoiDiem)
  activate PDS
deactivate PDS
  LPDS -> PDS : ApDungChinhSachHoanCoc(chinhSach.TiLe_ChuaKy)
  activate PDS
deactivate PDS
  LPDS -> PDS : TinhTongKhauTru(0)
  activate PDS
deactivate PDS
  LPDS -> PDS : ChotKetQua(phieuThu.SoTienThu)
  activate PDS
deactivate PDS
else loaiHoSo = HopDong
  LPDS -> HD : LayThongTinLuuTru(maHoSo)
  activate HD
  HD -> HDDB : LayThongTinLuuTru(maHoSo)
  activate HDDB
deactivate HDDB
deactivate HD
  LPDS -> HD : TinhSoThangThucTe(thoiDiem)
  activate HD
deactivate HD
  LPDS -> HD : TinhSoThangHopDong()
  activate HD
  alt hopDong.MaChinhSach co gia tri
deactivate HD
    LPDS -> CS : LayChinhSachTheoMa(hopDong.MaChinhSach)
    activate CS
    CS -> CSDB : GetChinhSachTheoMa(hopDong.MaChinhSach)
    activate CSDB
deactivate CSDB
  else hop dong cu chua gan chinh sach
deactivate CS
    LPDS -> CS : LayChinhSachDangApDung(homNay)
    activate CS
    CS -> CSDB : LayChinhSachDangApDung(homNay)
    activate CSDB
deactivate CSDB
  end
deactivate CS
  LPDS -> HDON : LayDanhSachChuaThanhToan(maHoSo)
  activate HDON
  HDON -> HDONDB : GetDanhSachChuaThanhToanTheoHD(maHoSo)
  activate HDONDB
deactivate HDONDB
deactivate HDON
  LPDS -> PDS : TaoMoi(maPhieuCoc, maHoSo, null, thoiDiem)
  activate PDS
deactivate PDS
  LPDS -> PDS : TinhToanDoiSoat(tienCoc, tyLe, dsHoaDon)
  activate PDS
deactivate PDS
end

deactivate LPDS
KT -> MH : xac nhan tao phieu doi soat
MH -> MH : handleCreate()
MH -> LPDS : TaoPhieuDoiSoat(maHoSo, loaiHoSo, ghiChu, maNhanVien)
activate LPDS
LPDS -> LPDS : LayChiTietVaTinhToanInternal(maHoSo, loaiHoSo)
LPDS -> PDS : LuuPhieu()
activate PDS
note right of PDS
  PDS moi co TrangThai = ChoXacNhan
end note
PDS -> PDSDB : LuuPhieu(phieu)
activate PDSDB
deactivate PDSDB
deactivate PDS
LPDS -> TB : GuiThongBaoQuanLy(maPDS)
activate TB
deactivate TB
deactivate LPDS
deactivate MH
@enduml
