@startuml
title SO DO TUAN TU - LAP PHIEU THU
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Ke toan" as KT
box "GUI" #D5F5D3
boundary ": MHLapPhieuThu" as MH
end box
box "BUS" #FCF3CF
control ": ThanhToanTraPhong" as UC
control ": PhieuDoiSoat" as PDS
control ": PhieuThu" as PT
end box
box "DB" #D6EAF8
entity ": PhieuDoiSoatDB" as PDSDB
entity ": PhieuThuDB" as PTDB
end box

KT -> MH : Mo man hinh lap phieu thu tu phieu doi soat
activate MH
MH -> MH : taiChiTiet(maPDS)
MH -> UC : LayChiTietPhieuDoiSoat(maPDS)
activate UC
UC -> PDS : LayChiTietPhieuDoiSoat(maPDS)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatTheoMaPDS(maPDS)
activate PDSDB
deactivate PDSDB
deactivate PDS
deactivate UC

KT -> MH : Chon phuong thuc, tai minh chung va nhan "Xac nhan thu tien"
MH -> MH : xacNhanThuTien()
MH -> UC : TienHanhThuTien(maPDS, phuongThuc, anhMinhChung, maNV)
activate UC
UC -> PDS : LayChiTietPhieuDoiSoat(maPDS)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatTheoMaPDS(maPDS)
activate PDSDB
deactivate PDSDB
deactivate PDS
UC -> PT : DaTonTaiChoPhieuDoiSoat(maPDS)
activate PT
PT -> PTDB : TonTaiTheoMaPhieuDoiSoat(maPDS)
activate PTDB
deactivate PTDB
deactivate PT
UC -> PT : TaoPhieuThu(maPDS, tienThuThem, phuongThuc, anhMinhChung, maNV, thoiDiem)
activate PT
deactivate PT
UC -> PT : LuuPhieu()
activate PT
PT -> PTDB : InsertPhieuThu(phieuThu)
activate PTDB
deactivate PTDB
deactivate PT
UC -> PDS : ChuyenSangDaTatToan(maPDS)
activate PDS
PDS -> PDSDB : UpdateTrangThai(maPDS, "DaChot", "DaTatToan")
activate PDSDB
deactivate PDSDB
deactivate PDS
deactivate UC
deactivate MH
@enduml
