@startuml
title SO DO TUAN TU - LAP PHIEU HOAN COC
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Ke toan" as KT

box "GUI" #D5F5D3
boundary ": MHHoanCoc" as MH
end box

box "BUS" #FCF3CF
control ": LapPhieuHoanCoc" as LPHC
control ": PhieuDoiSoat" as PDS
control ": PhieuHoanCoc" as PHC
end box

box "DB" #D6EAF8
entity ": PhieuDoiSoatDB" as PDSDB
entity ": PhieuHoanCocDB" as PHCDB
end box

KT -> MH : mo man hinh hoan coc
activate MH
MH -> MH : fetchQueue()
MH -> LPHC : LayDSPhieuDoiSoatCanHoan()
activate LPHC
LPHC -> PDS : LayDSPhieuDoiSoatCanHoan()
activate PDS
PDS -> PDSDB : GetDSPhieuDoiSoatCanHoan()
activate PDSDB
deactivate PDSDB
deactivate PDS
deactivate LPHC
KT -> MH : chon phieu doi soat
MH -> MH : fetchDetails(maPDS)
MH -> LPHC : LayChiTietPhieuDoiSoatDto(maPDS)
activate LPHC
LPHC -> PDS : LayChiTietPhieuDoiSoat(maPDS)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatTheoMaPDS(maPDS)
activate PDSDB

deactivate PDSDB
deactivate PDS
deactivate LPHC
KT -> MH : nhap phuong thuc va xac nhan hoan
MH -> MH : handleSubmit(values)
MH -> LPHC : ThucHienHoanCoc(maPDS, phuongThuc, thongTinNhanTien, maGiaoDich, minhChung, maNV)
activate LPHC
LPHC -> PDS : LayChiTietChoCapNhat(maPDS)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatChoCapNhat(maPDS)
activate PDSDB
deactivate PDSDB
deactivate PDS
LPHC -> PHC : DaTonTaiChoPhieuDoiSoat(maPDS)
activate PHC
PHC -> PHCDB : TonTaiTheoMaPhieuDoiSoat(maPDS)
activate PHCDB
deactivate PHCDB
deactivate PHC
LPHC -> PHC : TaoPhieuHoanCoc(maPDS, pds.TienHoan, phuongThuc, thongTinNhanTien, maNV, thoiDiem)
activate PHC
deactivate PHC
LPHC -> PHC : LuuPhieu()
activate PHC
PHC -> PHCDB : InsertPhieuHoanCoc(phieu)
activate PHCDB
deactivate PHCDB
deactivate PHC
LPHC -> PDS : ChuyenSangDaTatToan(maPDS)
activate PDS
PDS -> PDSDB : UpdateTrangThai(maPDS, DaChot, DaTatToan)
activate PDSDB
deactivate PDSDB
deactivate PDS
deactivate LPHC
deactivate MH
@enduml
