@startuml
title USE CASE - TRA CUU VA HUY PHIEU COC
left to right direction
actor "Nhan vien Sale" as Sale
actor "Quan ly" as QL
actor "Ke toan" as KT
usecase "Tra cuu phieu coc" as TraCuu
usecase "Huy phieu coc" as Huy
Sale -- TraCuu
QL -- TraCuu
KT -- TraCuu
Sale -- Huy
Huy ..> TraCuu : <<include>>
@enduml
