@startuml
title Quản lý quy định lưu trú
skinparam responseMessageBelowArrow true

boundary MHQuanLyQuyDinh
control QuanLyQuyDinh
control QuyDinh
entity QuyDinhDB
entity QuyDinhFileStorage

MHQuanLyQuyDinh -> QuanLyQuyDinh: LayDanhSach()
QuanLyQuyDinh -> QuyDinh: LayDanhSach()
QuyDinh -> QuyDinhDB: LayDanhSach()

MHQuanLyQuyDinh -> QuanLyQuyDinh: Them(quyDinh, tep)
QuanLyQuyDinh -> QuyDinh: ChuanHoa()
QuanLyQuyDinh -> QuyDinh: KiemTraDuLieuHopLe(false)
QuanLyQuyDinh -> QuyDinhFileStorage: Luu(tep)
QuanLyQuyDinh -> QuyDinh: TaoMaMoi()
QuyDinh -> QuyDinhDB: TaoMaMoi()
QuanLyQuyDinh -> QuyDinh: Them()
QuyDinh -> QuyDinhDB: Them(quyDinh)

MHQuanLyQuyDinh -> QuanLyQuyDinh: CapNhat(maQD, thongTin, tepMoi)
QuanLyQuyDinh -> QuyDinh: Doc(maQD)
QuyDinh -> QuyDinhDB: Doc(maQD)
QuanLyQuyDinh -> QuyDinh: KiemTraDuLieuHopLe(true)
QuanLyQuyDinh -> QuyDinh: CapNhat()
QuyDinh -> QuyDinhDB: CapNhat(quyDinh)

MHQuanLyQuyDinh -> QuanLyQuyDinh: Xoa(maQD)
QuanLyQuyDinh -> QuyDinh: Doc(maQD)
QuyDinh -> QuyDinhDB: Doc(maQD)
QuanLyQuyDinh -> QuyDinh: DangDuocThamChieu(maQD)
QuyDinh -> QuyDinhDB: DangDuocThamChieu(maQD)
QuanLyQuyDinh -> QuyDinh: Xoa()
QuyDinh -> QuyDinhDB: Xoa(maQD)
QuanLyQuyDinh -> QuyDinhFileStorage: Xoa(duongDan)

MHQuanLyQuyDinh -> QuanLyQuyDinh: DocVanBan(tenTep)
QuanLyQuyDinh -> QuyDinhFileStorage: Doc(tenTep)
@enduml
