@startuml
title SO DO TUAN TU - QUAN LY PHONG GIUONG

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Quan tri vien" as QT

box "GUI" #D5F5D3
boundary ": MHQuanLyPhongGiuong" as MH
end box

box "BUS" #FCF3CF
control ": QuanLyPhongGiuong" as QL
control ": Phong" as P
control ": Giuong" as G
control ": LoaiPhong" as LP
control ": ChiNhanh" as CN
end box

box "DB" #D6EAF8
entity ": PhongDB" as PDB
entity ": GiuongDB" as GDB
entity ": LoaiPhongDB" as LPDB
entity ": ChiNhanhDB" as CNDB
end box

QT -> MH : Chon chuc nang va mo man hinh
MH -> MH : HienThi()
activate MH
MH -> QL : LayDanhSachPhong("", "", "", "")
activate QL
QL -> P : LayDanhSachQuanTri("", "", "", "")
activate P
P -> PDB : LayDanhSachQuanTri("", "", "", "")
activate PDB
deactivate PDB
deactivate P
deactivate QL
MH -> QL : LayDanhSachGiuong("", "", "")
activate QL
QL -> G : LayDanhSachQuanTri("", "", "")
activate G
G -> GDB : LayDanhSachQuanTri("", "", "")
activate GDB
deactivate GDB
deactivate G
deactivate QL
MH -> QL : LayDanhSachLoaiPhong()
activate QL
QL -> LP : LayDanhSach()
activate LP
LP -> LPDB : LayDanhSach()
activate LPDB
deactivate LPDB
deactivate LP
deactivate QL
MH -> QL : LayDanhSachChiNhanh()
activate QL
QL -> CN : LayDanhSach()
activate CN
CN -> CNDB : LayDanhSach()
activate CNDB
deactivate CNDB
deactivate CN
deactivate QL

alt Them phong
  QT -> MH : Nhan "Them phong"
  MH -> MH : moFormThemPhong()
  QT -> MH : Nhap thong tin phong va nhan "Luu"
  MH -> MH : luuPhong(phong)
  MH -> QL : ThemPhong(phong)
  activate QL
  QL -> P : ChuanHoa()
  activate P
  QL -> P : KiemTraDuLieuHopLe()
  deactivate P
  QL -> LP : LayTheoMa(maLP)
  activate LP
  LP -> LPDB : LayTheoMa(maLP)
  activate LPDB
  deactivate LPDB
  deactivate LP
  QL -> CN : TonTai(maCN)
  activate CN
  CN -> CNDB : TonTai(maCN)
  activate CNDB
  deactivate CNDB
  deactivate CN
  QL -> P : TrungSoPhong(maCN, soPhong, "")
  activate P
  P -> PDB : TrungSoPhong(maCN, soPhong, "")
  activate PDB
  deactivate PDB
  deactivate P
  QL -> P : Them()
  activate P
  P -> PDB : Them(phong)
  activate PDB
  deactivate PDB
  deactivate P
  deactivate QL
else Sua phong
  QT -> MH : Chon phong va nhan "Sua"
  MH -> MH : moFormSuaPhong(phong)
  QT -> MH : Nhap thong tin phong va nhan "Luu"
  MH -> MH : luuPhong(phong)
  MH -> QL : CapNhatPhong(maPhong, thongTin)
  activate QL
  QL -> P : ChuanHoa()
  activate P
  QL -> P : KiemTraDuLieuHopLe()
  deactivate P
  QL -> P : DocChiTiet(maPhong)
  activate P
  P -> PDB : DocChiTiet(maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  QL -> LP : LayTheoMa(maLP)
  activate LP
  LP -> LPDB : LayTheoMa(maLP)
  activate LPDB
  deactivate LPDB
  deactivate LP
  QL -> CN : TonTai(maCN)
  activate CN
  CN -> CNDB : TonTai(maCN)
  activate CNDB
  deactivate CNDB
  deactivate CN
  QL -> P : TrungSoPhong(maCN, soPhong, maPhong)
  activate P
  P -> PDB : TrungSoPhong(maCN, soPhong, maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  QL -> P : DangDuocThamChieu(maPhong)
  activate P
  P -> PDB : DangDuocThamChieu(maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  QL -> P : KiemTraSucChuaChoDoiLoaiPhong(sucChuaMoi, soGiuongHienCo)
  activate P
  QL -> P : KiemTraDoiTrangThai(trangThaiMoi, giuongHienCo, dangDuocThamChieu)
  deactivate P
  QL -> P : CapNhatThongTin()
  activate P
  P -> PDB : CapNhatThongTin(phong)
  activate PDB
  deactivate PDB
  deactivate P
  deactivate QL
else Xoa phong
  QT -> MH : Chon ban ghi va xac nhan xoa
  MH -> MH : xacNhanXoa()
  MH -> QL : XoaPhong(maPhong)
  activate QL
  QL -> P : DocChiTiet(maPhong)
  activate P
  P -> PDB : DocChiTiet(maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  QL -> P : KiemTraCoTheXoa()
  activate P
  deactivate P
  QL -> P : DangDuocThamChieu(maPhong)
  activate P
  P -> PDB : DangDuocThamChieu(maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  QL -> P : Xoa()
  activate P
  P -> PDB : Xoa(maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  deactivate QL
else Them giuong
  QT -> MH : Nhan "Them giuong"
  MH -> MH : moFormThemGiuong()
  QT -> MH : Nhap thong tin giuong va nhan "Luu"
  MH -> MH : luuGiuong(giuong)
  MH -> QL : ThemGiuong(giuong)
  activate QL
  QL -> G : ChuanHoa()
  activate G
  QL -> G : KiemTraDuLieuHopLe()
  deactivate G
  QL -> P : DocChiTiet(maPhong)
  activate P
  P -> PDB : DocChiTiet(maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  QL -> G : TrungSoGiuong(maPhong, soGiuong, "")
  activate G
  G -> GDB : TrungSoGiuong(maPhong, soGiuong, "")
  activate GDB
  deactivate GDB
  deactivate G
  QL -> P : KiemTraSoGiuongKhongVuotSucChua(soGiuongHienCo)
  activate P
  deactivate P
  QL -> G : Them()
  activate G
  G -> GDB : Them(giuong)
  activate GDB
  deactivate GDB
  deactivate G
  deactivate QL
else Sua giuong
  QT -> MH : Chon giuong va nhan "Sua"
  MH -> MH : moFormSuaGiuong(giuong)
  QT -> MH : Nhap thong tin giuong va nhan "Luu"
  MH -> MH : luuGiuong(giuong)
  MH -> QL : CapNhatGiuong(maGiuong, thongTin)
  activate QL
  QL -> G : ChuanHoa()
  activate G
  QL -> G : KiemTraDuLieuHopLe()
  deactivate G
  QL -> G : DocChiTiet(maGiuong)
  activate G
  G -> GDB : DocChiTiet(maGiuong)
  activate GDB
  deactivate GDB
  deactivate G
  QL -> P : DocChiTiet(maPhong)
  activate P
  P -> PDB : DocChiTiet(maPhong)
  activate PDB
  deactivate PDB
  deactivate P
  QL -> G : TrungSoGiuong(maPhong, soGiuong, maGiuong)
  activate G
  G -> GDB : TrungSoGiuong(maPhong, soGiuong, maGiuong)
  activate GDB
  deactivate GDB
  deactivate G
  QL -> G : DangDuocThamChieu(maGiuong)
  activate G
  G -> GDB : DangDuocThamChieu(maGiuong)
  activate GDB
  deactivate GDB
  deactivate G
  QL -> G : KiemTraCoTheDoiSoGiuong(dangDuocThamChieu)
  activate G
  QL -> G : KiemTraCoTheChuyenPhong(dangDuocThamChieu)
  deactivate G
  QL -> P : KiemTraSoGiuongKhongVuotSucChua(soGiuongHienCo)
  activate P
  deactivate P
  QL -> G : KiemTraDoiTrangThai(trangThaiMoi, dangDuocThamChieu)
  activate G
  deactivate G
  QL -> G : CapNhatThongTin()
  activate G
  G -> GDB : CapNhatThongTin(giuong)
  activate GDB
  deactivate GDB
  deactivate G
  deactivate QL
else Xoa giuong
  QT -> MH : Chon ban ghi va xac nhan xoa
  MH -> MH : xacNhanXoa()
  MH -> QL : XoaGiuong(maGiuong)
  activate QL
  QL -> G : DocChiTiet(maGiuong)
  activate G
  G -> GDB : DocChiTiet(maGiuong)
  activate GDB
  deactivate GDB
  deactivate G
  QL -> G : KiemTraCoTheXoa()
  activate G
  deactivate G
  QL -> G : DangDuocThamChieu(maGiuong)
  activate G
  G -> GDB : DangDuocThamChieu(maGiuong)
  activate GDB
  deactivate GDB
  deactivate G
  QL -> G : Xoa()
  activate G
  G -> GDB : Xoa(maGiuong)
  activate GDB
  deactivate GDB
  deactivate G
  deactivate QL
end

deactivate MH
@enduml
