@startuml
title SO DO TUAN TU - TAO LICH HEN
hide footbox
autonumber
skinparam shadowing false

actor "Nhan vien Sale" as Sale

box "GUI" #D5F5D3
boundary ": MHTaoLichHen" as MH
end box

box "BUS" #FCF3CF
control ": TaoLichHen" as TLH
control ": NhanVien" as NV
control ": LichHen" as LH
end box

box "DB" #D6EAF8
entity ": NhanVienDB" as NVDB
entity ": LichHenDB" as LHDB
end box

Sale -> MH : Mo man hinh chuc nang
activate MH
MH -> MH : HienThi()
Sale -> MH : Nhap tieu chi va chon Tim kiem
MH -> MH : TimChungTu(loai, tuKhoa)
MH -> TLH : TaiDanhSachChungTu(loai, tuKhoa, maNV)
activate TLH
TLH -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB

deactivate NVDB
deactivate NV
deactivate TLH
Sale -> MH : Nhan nut thao tac tren giao dien
MH -> MH : LuuLichHen()
MH -> TLH : LuuLichHen(loai, maChungTu, ngayHen, gioHen, maNV)
activate TLH
TLH -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
TLH -> LH : TaoMoi(loai, maChungTu, maCN, ngayHen, gioHen, maNV, thoiDiem)
activate LH
deactivate LH
TLH -> LH : KiemTraThoiGianHopLe(thoiDiem)
activate LH
deactivate LH
TLH -> LH : KiemTraHopLe()
activate LH
deactivate LH
TLH -> LH : KiemTraTrungLich()
activate LH
LH -> LHDB : KiemTraLichTrungCaNhanVien(maNV, ngayHen, gioHen)
activate LHDB
alt Hop le va khong trung lich
deactivate LHDB
deactivate LH
  TLH -> LH : Them()
  activate LH
  LH -> LHDB : Them(lichHen)
  activate LHDB
else Sai chi nhanh, trang thai hoac trung lich
deactivate LHDB
deactivate LH
end
deactivate TLH
deactivate MH
@enduml
