@startuml
title SO DO TUAN TU - THANH LY HOP DONG

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Quan ly" as QL

box "GUI" #D5F5D3
boundary ": MHThanhLyHopDong" as MH
end box

box "BUS" #FCF3CF
control ": HopDong" as HD
control ": PhieuDoiSoat" as PDS
control ": PhieuCoc" as PC
control ": ThanhVienHopDong" as TV
control ": DichVuHopDong" as DV
control ": Giuong" as G
end box

box "DB" #D6EAF8
entity ": HopDongDB" as HDDB
entity ": PhieuDoiSoatDB" as PDSDB
entity ": PhieuCocDB" as PCDB
entity ": ThanhVienHopDongDB" as TVDB
entity ": DichVuHopDongDB" as DVDB
entity ": GiuongDB" as GDB
end box

QL -> MH : Mo man hinh thanh ly hop dong
activate MH
MH -> MH : taiDanhSach(tuKhoa)
MH -> HD : LayDanhSachChoThanhLy(tuKhoa)
activate HD
HD -> HDDB : LayDanhSachChoThanhLy(tuKhoa)
activate HDDB
deactivate HDDB
deactivate HD

QL -> MH : Chon hop dong
MH -> MH : chonHopDong(maHD)
MH -> HD : LayThongTinHopDong(maHD)
activate HD
HD -> HD : DocChiTiet(maHD)
HD -> HDDB : DocChiTiet(maHD)
activate HDDB
deactivate HDDB
HD -> TV : LayDanhSachTheoHopDong(maHD)
activate TV
TV -> TVDB : LayDanhSachTheoHopDong(maHD)
activate TVDB
deactivate TVDB
deactivate TV
HD -> DV : LayDanhSachTheoHopDong(maHD)
activate DV
DV -> DVDB : LayDanhSachTheoHopDong(maHD)
activate DVDB
deactivate DVDB
deactivate DV
deactivate HD
MH -> PDS : LayThongTinDoiSoat(maHD)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatTheoMaHD(maHD)
activate PDSDB
deactivate PDSDB
deactivate PDS
MH -> PDS : KiemTraCongNo(pds)
activate PDS
deactivate PDS

QL -> MH : Xac nhan da ky bien ban va thu hoi chia khoa
QL -> MH : Nhan "Thanh ly"
MH -> MH : xacNhanThanhLy()
MH -> HD : LayThongTinHopDong(maHD)
activate HD
HD -> HD : DocChiTiet(maHD)
HD -> HDDB : DocChiTiet(maHD)
activate HDDB
deactivate HDDB
HD -> TV : LayDanhSachTheoHopDong(maHD)
activate TV
TV -> TVDB : LayDanhSachTheoHopDong(maHD)
activate TVDB
deactivate TVDB
deactivate TV
HD -> DV : LayDanhSachTheoHopDong(maHD)
activate DV
DV -> DVDB : LayDanhSachTheoHopDong(maHD)
activate DVDB
deactivate DVDB
deactivate DV
HD -> HD : KiemTraDangHieuLuc()
deactivate HD
MH -> PC : DocChiTiet(maPhieuCoc)
activate PC
PC -> PC : DocChiTietHeThong(maPhieuCoc, false)
PC -> PCDB : DocChiTietHeThong(maPhieuCoc, false)
activate PCDB
deactivate PCDB
deactivate PC
MH -> PDS : LayThongTinDoiSoat(maHD)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatTheoMaHD(maHD)
activate PDSDB
deactivate PDSDB
PDS -> PDS : KiemTraCongNo(pds)
deactivate PDS

alt Da hoan tat nghia vu tai chinh
  MH -> HD : ThanhLyHopDong(maHD, ngayThanhLy, maNV, ghiChu)
  activate HD
  HD -> HDDB : UpdateTrangThaiThanhLy(maHD)
  activate HDDB
  deactivate HDDB
  deactivate HD
  opt Chua co danh sach thanh vien trong chi tiet hop dong
    MH -> TV : LayDanhSachGiuong(maHD)
    activate TV
    TV -> TV : LayDanhSachTheoHopDong(maHD)
    TV -> TVDB : LayDanhSachTheoHopDong(maHD)
    activate TVDB
    deactivate TVDB
    deactivate TV
  end
  opt Hop dong co giuong dang thue
    MH -> TV : CapNhatTrangThaiDaTra(maHD, ngayTra)
    activate TV
    TV -> TVDB : UpdateTrangThaiDaTra(maHD, ngayTra)
    activate TVDB
    deactivate TVDB
    deactivate TV
    MH -> G : CapNhatDanhSachTrong(dsMaGiuong)
    activate G
    G -> GDB : UpdateTrangThaiBatch(dsMaGiuong, "Trong")
    activate GDB
    deactivate GDB
    deactivate G
  end
else Con cong no hoac ho so khong hop le
end

deactivate MH
@enduml
