@startuml
title SO DO TUAN TU - THANH TOAN TRA PHONG
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Ke toan" as KT
box "GUI" #D5F5D3
boundary ": MHThanhToanTraPhong" as MH
end box
box "BUS" #FCF3CF
control ": ThanhToanTraPhong" as UC
control ": PhieuDoiSoat" as PDS
control ": HopDong" as HD
control ": PhieuCoc" as PC
control ": HoaDon" as HDon
control ": PhieuThu" as PT
end box
box "DB" #D6EAF8
entity ": PhieuDoiSoatDB" as PDSDB
entity ": HopDongDB" as HDDB
entity ": PhieuCocDB" as PCDB
entity ": HoaDonDB" as HDonDB
entity ": PhieuThuDB" as PTDB
end box

KT -> MH : Chon chuc nang "Thanh toan tra phong"
activate MH
MH -> MH : taiDanhSach()
MH -> UC : LayDSPhieuDoiSoatDaChot()
activate UC
UC -> PDS : LayDSPhieuDoiSoatDaChot()
activate PDS
PDS -> PDSDB : GetDSPhieuDoiSoatDaChot()
activate PDSDB
deactivate PDSDB
deactivate PDS
deactivate UC

KT -> MH : Chon phieu doi soat
MH -> MH : chonPhieuDoiSoat(maPDS)
MH -> UC : LayChiTietPhieuDoiSoat(maPDS)
activate UC
UC -> PDS : LayChiTietPhieuDoiSoat(maPDS)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatTheoMaPDS(maPDS)
activate PDSDB
deactivate PDSDB
deactivate PDS
alt Phieu doi soat co hop dong
  UC -> HD : LayThongTinLuuTru(maHD)
  activate HD
  HD -> HDDB : LayThongTinLuuTru(maHD)
  activate HDDB
  deactivate HDDB
  deactivate HD
else Phieu coc huy truoc hop dong
  UC -> PC : DocChiTiet(maPhieuCoc)
  activate PC
  PC -> PCDB : DocChiTietHeThong(maPhieuCoc)
  activate PCDB
  deactivate PCDB
  deactivate PC
end
UC -> HDon : LayDSHoaDonTheoPhieuDoiSoat(maPDS)
activate HDon
HDon -> HDonDB : GetDSHoaDonTheoMaPDS(maPDS)
activate HDonDB
deactivate HDonDB
deactivate HDon
deactivate UC

KT -> MH : Chon phuong thuc, tai minh chung va nhan "Thu tien"
MH -> MH : xacNhanThuTien()
MH -> UC : TienHanhThuTien(maPDS, phuongThuc, anhMinhChung, maNV)
activate UC
UC -> PDS : LayChiTietPhieuDoiSoat(maPDS)
activate PDS
PDS -> PDSDB : GetPhieuDoiSoatTheoMaPDS(maPDS)
activate PDSDB
deactivate PDSDB
deactivate PDS
UC -> PT : DaTonTaiChoPhieuDoiSoat(maPDS)
activate PT
PT -> PTDB : TonTaiTheoMaPhieuDoiSoat(maPDS)
activate PTDB
deactivate PTDB
deactivate PT
UC -> PT : TaoPhieuThu(maPDS, tienThuThem, phuongThuc, anhMinhChung, maNV, thoiDiem)
activate PT
deactivate PT
UC -> PT : LuuPhieu()
activate PT
PT -> PTDB : InsertPhieuThu(phieuThu)
activate PTDB
deactivate PTDB
deactivate PT
UC -> PDS : ChuyenSangDaTatToan(maPDS)
activate PDS
PDS -> PDSDB : UpdateTrangThai(maPDS, "DaChot", "DaTatToan")
activate PDSDB
deactivate PDSDB
deactivate PDS
deactivate UC
deactivate MH
@enduml
