@startuml
title SO DO TUAN TU - TINH TIEN COC

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Ke toan" as KT

box "GUI" #D5F5D3
boundary ": MHTinhTienCoc" as MH
end box

box "BUS" #FCF3CF
control ": TinhTienCoc" as TTC
control ": NhanVien" as NV
control ": PhieuCoc" as PC
control ": Phong" as P
end box

box "DB" #D6EAF8
entity ": NhanVienDB" as NVDB
entity ": PhieuCocDB" as PCDB
end box

KT -> MH : Chon chuc nang "Tinh tien coc"
activate MH
MH -> MH : taiDanhSach(text)
MH -> TTC : LayDanhSachKhoiTao(text, maNV)
activate TTC
TTC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
TTC -> PC : LayDanhSachKhoiTao(maCN, text)
activate PC
PC -> PCDB : LayDanhSachKhoiTao(maCN, text)
activate PCDB
deactivate PCDB
deactivate PC
deactivate TTC

KT -> MH : Chon mot phieu coc
MH -> MH : chonPhieuCoc(maPhieuCoc)
MH -> TTC : LayChiTietVaTinhTien(maPhieuCoc, maNV)
activate TTC
TTC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
TTC -> PC : DocChiTiet(maPhieuCoc, maCN)
activate PC
PC -> PCDB : DocChiTiet(maPhieuCoc, maCN)
activate PCDB
deactivate PCDB
deactivate PC
TTC -> PC : TinhTienDuKien()
activate PC
PC -> PC : KiemTraCoTheTinhTien()
PC -> P : TinhTienCoc(soGiuongThue)
activate P
deactivate P
deactivate PC
deactivate TTC

KT -> MH : Nhan "Xac nhan"
MH -> MH : xacNhan()
MH -> TTC : XacNhanTinhTien(maPhieuCoc, maNV)
activate TTC
TTC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
TTC -> PC : DocChiTietChoCapNhat(maPhieuCoc, maCN)
activate PC
PC -> PCDB : DocChiTietChoCapNhat(maPhieuCoc, maCN)
activate PCDB
deactivate PCDB
deactivate PC
TTC -> PC : XacNhanTinhTien(thoiDiemXacNhan, thoiHanThanhToan)
activate PC
PC -> PC : TinhTienDuKien()
PC -> PC : KiemTraCoTheTinhTien()
PC -> P : TinhTienCoc(soGiuongThue)
activate P
deactivate P
deactivate PC
TTC -> PC : CapNhatTinhTien()
activate PC
PC -> PCDB : CapNhatTinhTien(phieu)
activate PCDB
deactivate PCDB
deactivate PC
deactivate TTC

MH -> MH : taiDanhSach(text)
MH -> TTC : LayDanhSachKhoiTao(text, maNV)
activate TTC
TTC -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
TTC -> PC : LayDanhSachKhoiTao(maCN, text)
activate PC
PC -> PCDB : LayDanhSachKhoiTao(maCN, text)
activate PCDB
deactivate PCDB
deactivate PC
deactivate TTC

deactivate MH
@enduml
