@startuml
title SO DO TUAN TU - TRA CUU PHIEU COC
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Nguoi dung" as ND
boundary ": MHTraCuuPhieuCoc" as MH
control ": TraCuuPhieuCoc" as TC
control ": PhieuCoc" as PC
entity ": PhieuCocDB" as PCDB
ND -> MH : btnTimKiem_Click()
MH -> TC : TimKiem(maPhieuCoc, sdt, email, soGiayTo)
TC -> TC : kiem tra co it nhat mot tieu chi
TC -> PC : TraCuu(maPhieuCoc, sdt, email, soGiayTo)
PC -> PCDB : TraCuu(maPhieuCoc, sdt, email, soGiayTo)
ND -> MH : grvKetQua_CellClick(maPhieuCoc)
MH -> TC : LayChiTiet(maPhieuCoc)
TC -> PC : DocChiTiet(maPhieuCoc)
PC -> PCDB : DocChiTiet(maPhieuCoc)
@enduml
