@startuml
title Sequence - UC Tra cứu phòng/giường

skinparam dpi 180
skinparam shadowing false
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor "Nhân viên Sale" as NV

box "GUI" #D5F5D3
boundary MHTraCuuPhongGiuong
end box

box "BUS" #FCF3CF
control ChiNhanh
control LoaiPhong
control Phong
control Giuong
control "Phong_TaiSan" as PhongTaiSan
end box

box "DB" #D6EAF8
entity ChiNhanhDB
entity LoaiPhongDB
entity PhongDB
entity GiuongDB
entity "Phong_TaiSanDB" as PhongTaiSanDB
end box

== Khởi tạo màn hình ==

NV -> MHTraCuuPhongGiuong : 1.0 Chức năng tra cứu phòng/giường
activate MHTraCuuPhongGiuong

MHTraCuuPhongGiuong -> ChiNhanh : 1.1 layDanhSach()
activate ChiNhanh

ChiNhanh -> ChiNhanhDB : 1.2 layDanhSach()
activate ChiNhanhDB
deactivate ChiNhanhDB
deactivate ChiNhanh

MHTraCuuPhongGiuong -> LoaiPhong : 1.3 layDanhSach()
activate LoaiPhong

LoaiPhong -> LoaiPhongDB : 1.4 layDanhSach()
activate LoaiPhongDB
deactivate LoaiPhongDB
deactivate LoaiPhong

== Lọc phòng ==

alt Không nhập tiêu chí

NV -> MHTraCuuPhongGiuong : Chọn bộ lọc
MHTraCuuPhongGiuong -> MHTraCuuPhongGiuong : boLocThayDoi_Handler()

MHTraCuuPhongGiuong -> Phong : locPhongTheoTieuChi()
activate Phong

Phong -> PhongDB : layPhongTheoBoLoc()
activate PhongDB
deactivate PhongDB

loop Với mỗi phòng

Phong -> Giuong : layDanhSachGiuong(maPhong)
activate Giuong

Giuong -> GiuongDB : layGiuongTheoPhong(maPhong)
activate GiuongDB
deactivate GiuongDB

deactivate Giuong

end

deactivate Phong

else Có nhập tiêu chí

NV -> MHTraCuuPhongGiuong : Chọn bộ lọc
MHTraCuuPhongGiuong -> MHTraCuuPhongGiuong : boLocThayDoi_Handler()

MHTraCuuPhongGiuong -> Phong : locPhongTheoTieuChi(toaNha,tang,maLP,maCN,trangThai,giaMin,giaMax)
activate Phong

Phong -> PhongDB : layPhongTheoBoLoc(toaNha,tang,maLP,maCN,trangThai,giaMin,giaMax)
activate PhongDB
deactivate PhongDB

loop Với mỗi phòng

Phong -> Giuong : layDanhSachGiuong(maPhong)
activate Giuong

Giuong -> GiuongDB : layGiuongTheoPhong(maPhong)
activate GiuongDB
deactivate GiuongDB

deactivate Giuong

end

deactivate Phong

end

MHTraCuuPhongGiuong -> MHTraCuuPhongGiuong : 2.0 hienThiDanhSachPhong(dsPhong)

== Xem tài sản ==

opt Bấm Xem tài sản

NV -> MHTraCuuPhongGiuong : Chọn phòng và nhấn "Xem tài sản"
MHTraCuuPhongGiuong -> MHTraCuuPhongGiuong : btnXemTaiSan_Click(maPhong)

MHTraCuuPhongGiuong -> Phong : layTaiSan(maPhong)
activate Phong

Phong -> PhongTaiSan : layTaiSanTheoPhong(maPhong)
activate PhongTaiSan

PhongTaiSan -> PhongTaiSanDB : layTaiSanTheoPhong(maPhong)
activate PhongTaiSanDB
deactivate PhongTaiSanDB

deactivate PhongTaiSan

deactivate Phong

MHTraCuuPhongGiuong -> MHTraCuuPhongGiuong : hienThiDanhSachTaiSan(dsTaiSan)

end
deactivate MHTraCuuPhongGiuong
@enduml
