@startuml
title SO DO TUAN TU - TRA CUU PHIEU DANG KY

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Nhan vien Sale" as Sale

box "GUI" #D5F5D3
boundary ": MHTraCuuPhieuDangKy" as MH
end box
box "BUS" #FCF3CF
control ": LapPhieuDangKy" as UC
control ": NhanVien" as NV
control ": PhieuDangKy" as PDK
end box
box "DB" #D6EAF8
entity ": NhanVienDB" as NVDB
entity ": PhieuDangKyDB" as PDKDB
end box

Sale -> MH : Chon chuc nang "Tra cuu phieu dang ky"
activate MH
MH -> MH : HienThi()

Sale -> MH : Nhap tieu chi tim kiem
Sale -> MH : Nhan "Tim kiem"
MH -> MH : timKiem(sdt, soGiayTo, email, hoTen, maPDK)
MH -> UC : TimKiemPhieuDangKy(sdt, soGiayTo, email, hoTen, maPDK, maNV)
activate UC
UC -> NV : DocPhamVi(maNV)
activate NV
NV -> NV : DocChiTiet(maNV)
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
UC -> PDK : TimKiem(maCN, sdt, soGiayTo, email, hoTen, maPDK)
activate PDK
PDK -> PDKDB : TimKiem(maCN, sdt, soGiayTo, email, hoTen, maPDK)
activate PDKDB
deactivate PDKDB
deactivate PDK
deactivate UC

Sale -> MH : Chon mot phieu dang ky
MH -> MH : chonPhieuDangKy(maPDK)
MH -> UC : LayChiTietPhieuDangKy(maPDK, maNV)
activate UC
UC -> NV : DocPhamVi(maNV)
activate NV
NV -> NV : DocChiTiet(maNV)
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
UC -> PDK : DocChiTiet(maPDK, maCN)
activate PDK
PDK -> PDKDB : LayTheoMa(maPDK, maCN)
activate PDKDB
deactivate PDKDB
deactivate PDK
deactivate UC
deactivate MH
@enduml
