@startuml
title SO DO TUAN TU - TRA CUU PHONG GIUONG

skinparam dpi 180
skinparam shadowing false
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor "Nhân viên Sale" as NV

box "GUI" #D5F5D3
boundary ": MHTraCuuPhongGiuong" as MH
end box

box "BUS" #FCF3CF
control ": ChiNhanh" as CN
control ": LoaiPhong" as LP
control ": Phong" as P
control ": PhongTaiSan" as PTS
end box

box "DB" #D6EAF8
entity ": ChiNhanhDB" as CNDB
entity ": LoaiPhongDB" as LPDB
entity ": PhongDB" as PDB
entity ": PhongTaiSanDB" as PTSDB
end box

== Khởi tạo màn hình ==

NV -> MH : Chon chuc nang "Tra cuu phong/giuong"
activate MH
MH -> MH : HienThi()

MH -> CN : LayDanhSach()
activate CN

CN -> CNDB : LayDanhSach()
activate CNDB
deactivate CNDB
deactivate CN

MH -> LP : LayDanhSach()
activate LP

LP -> LPDB : LayDanhSach()
activate LPDB
deactivate LPDB
deactivate LP

== Lọc phòng ==

alt Không nhập tiêu chí

NV -> MH : Chon bo loc
MH -> MH : thayDoiBoLoc()

MH -> P : LocPhongTheoTieuChi(null, null, null, maCN,\nnull, 0, 0)
activate P

P -> PDB : LayPhongTheoBoLoc(null, null, null, maCN,\nnull, 0, 0)
activate PDB
deactivate PDB

deactivate P

else Có nhập tiêu chí

NV -> MH : Chon bo loc
MH -> MH : thayDoiBoLoc()

MH -> P : LocPhongTheoTieuChi(toaNha, tang, maLP, maCN,\ntrangThai, giaMin, giaMax)
activate P

P -> PDB : LayPhongTheoBoLoc(toaNha, tang, maLP, maCN,\ntrangThai, giaMin, giaMax)
activate PDB
deactivate PDB

deactivate P

end


== Xem tài sản ==

opt Bấm Xem tài sản

NV -> MH : Chon phong va nhan "Xem tai san"
MH -> MH : xemTaiSan(maPhong)

MH -> P : LayTaiSan(maPhong)
activate P

P -> PTS : LayTaiSanTheoPhong(maPhong)
activate PTS

PTS -> PTSDB : LayTaiSanTheoPhong(maPhong)
activate PTSDB
deactivate PTSDB

deactivate PTS

deactivate P


end
deactivate MH
@enduml
