@startuml
title SO DO TUAN TU - TRA CUU PHIEU COC
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Nguoi dung" as ND

box "GUI" #D5F5D3
boundary ": MHTraCuuPhieuCoc" as MH
end box

box "BUS" #FCF3CF
control ": TraCuuPhieuCoc" as TC
control ": NhanVien" as NV
control ": PhieuCoc" as PC
end box

box "DB" #D6EAF8
entity ": NhanVienDB" as NVDB
entity ": PhieuCocDB" as PCDB
end box

ND -> MH : Mo man hinh chuc nang
activate MH
MH -> MH : HienThi()

ND -> MH : Nhan "Tim Kiem"
MH -> MH : btnTimKiem_Click()
MH -> TC : TimKiem(maPhieuCoc, sdt, email, soGiayTo, maNV)
activate TC
alt Khong co tieu chi tim kiem
else Co it nhat mot tieu chi
  TC -> NV : DocPhamVi(maNV)
  activate NV
  NV -> NVDB : DocChiTiet(maNV)
  activate NVDB
  deactivate NVDB
  deactivate NV
  TC -> PC : TraCuu(maCN, maPhieuCoc, sdt, email, soGiayTo)
  activate PC
  PC -> PCDB : TraCuu(maCN, maPhieuCoc, sdt, email, soGiayTo)
  activate PCDB
  opt Co phieu coc trong ket qua
deactivate PCDB
deactivate PC
deactivate TC
    ND -> MH : Chon phieu coc trong ket qua
    MH -> MH : grvKetQua_CellClick(maPhieuCoc)
    MH -> TC : LayChiTiet(maPhieuCoc, maNV)
    activate TC
    TC -> NV : DocPhamVi(maNV)
    activate NV
    NV -> NVDB : DocChiTiet(maNV)
    activate NVDB
    deactivate NVDB
    deactivate NV
    TC -> PC : DocChiTiet(maPhieuCoc, maCN)
    activate PC
    PC -> PCDB : DocChiTiet(maPhieuCoc, maCN)
    activate PCDB
  end
deactivate PCDB
deactivate PC
end
deactivate TC
deactivate MH
@enduml
