@startuml
title SO DO TUAN TU - XAC NHAN KHOAN TIEN COC

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Quan ly" as QL
boundary ": MHXacNhanKhoanTienCoc" as MH
control ": XacNhanKhoanTienCoc" as XN
control ": PhieuCoc" as PC
control ": PhieuThu" as PT
control ": Phong" as P
entity ": PhieuCocDB" as PCDB
entity ": PhieuThuDB" as PTDB
entity ": PhongDB" as PDB

QL -> MH : hienThiDanhSachPhieuChoDoiChieu(tuKhoa)
MH -> XN : LayDanhSachChoDoiChieu(tuKhoa)
XN -> PC : LayDanhSachChoDoiChieu(tuKhoa)
PC -> PCDB : LayDanhSachChoDoiChieu(tuKhoa)

QL -> MH : chonPhieuCoc(maPhieuCoc)
MH -> XN : LayChiTiet(maPhieuCoc)
XN -> PC : DocChiTiet(maPhieuCoc)
PC -> PCDB : DocChiTiet(maPhieuCoc)
XN -> PC : KiemTraCoTheXacNhanThanhToan()
MH -> MH : hien thi chi tiet va chung tu

alt Khoan coc hop le
  QL -> MH : xacNhanHopLe()
  MH -> XN : XacNhanHopLe(maPhieuCoc, maNhanVienQuanLy)
  XN -> PC : DocChiTiet(maPhieuCoc)
  PC -> PCDB : DocChiTiet(maPhieuCoc)
  XN -> PC : KiemTraCoTheXacNhanThanhToan()
  XN -> P : DocChiTiet(maPhong)
  P -> PDB : DocChiTiet(maPhong)
  XN -> P : XacNhanDatCoc(maGiuongs)
  XN -> PT : TaoChoTienCoc(phieuCoc, maNhanVienQuanLy, thoiGian)
  XN -> PC : XacNhanThanhToan()
  XN -> PC : CapNhatXacNhanThanhToan()
  PC -> PCDB : CapNhatXacNhanThanhToan(phieu)
  XN -> PT : Them()
  PT -> PTDB : Them(phieuThu)
  XN -> P : CapNhatDatCoc()
  P -> PDB : CapNhatDatCoc(phong)
  alt Co tranh chap trang thai hoac giuong
    XN --> MH : rollback va bao loi
  else Thanh cong
    XN --> MH : phieu coc va ma phieu thu
    MH -> MH : thong bao dat coc thanh cong
  end
else Chung tu can bo sung
  QL -> MH : yeuCauBoSung(lyDo)
  alt Ly do rong hoac qua 500 ky tu
    MH -> MH : hien thi loi ly do
  else Ly do hop le
    MH -> XN : YeuCauBoSung(maPhieuCoc, lyDo)
    XN -> PC : DocChiTiet(maPhieuCoc)
    PC -> PCDB : DocChiTiet(maPhieuCoc)
    XN -> PC : YeuCauBoSung(lyDo, thoiDiemYeuCau, thoiHanThanhToan)
    XN -> PC : CapNhatYeuCauBoSung()
    PC -> PCDB : CapNhatYeuCauBoSung(phieu)
    MH -> MH : thong bao da gui yeu cau
  end
end

@enduml
