@startuml
title SO DO TUAN TU - XAC NHAN KHOAN TIEN COC

hide footbox
autonumber 1 1
skinparam shadowing false

actor "Quan ly" as QL

box "GUI" #D5F5D3
boundary ": MHXacNhanKhoanTienCoc" as MH
end box

box "BUS" #FCF3CF
control ": XacNhanKhoanTienCoc" as XN
control ": NhanVien" as NV
control ": PhieuCoc" as PC
control ": PhieuThu" as PT
control ": Phong" as P
control ": Giuong" as G
end box

box "DB" #D6EAF8
entity ": NhanVienDB" as NVDB
entity ": PhieuCocDB" as PCDB
entity ": PhieuThuDB" as PTDB
entity ": PhongDB" as PDB
end box

QL -> MH : Mo man hinh chuc nang
activate MH
MH -> MH : hienThiDanhSachPhieuChoDoiChieu(tuKhoa)
MH -> XN : LayDanhSachChoDoiChieu(tuKhoa, maNV)
activate XN
XN -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
XN -> PC : LayDanhSachChoDoiChieu(maCN, tuKhoa)
activate PC
PC -> PCDB : LayDanhSachChoDoiChieu(maCN, tuKhoa)
activate PCDB

deactivate PCDB
deactivate PC
deactivate XN
QL -> MH : Chon phieu coc
MH -> MH : chonPhieuCoc(maPhieuCoc)
MH -> XN : LayChiTiet(maPhieuCoc, maNV)
activate XN
XN -> NV : DocPhamVi(maNV)
activate NV
NV -> NVDB : DocChiTiet(maNV)
activate NVDB
deactivate NVDB
deactivate NV
XN -> PC : DocChiTiet(maPhieuCoc, maCN)
activate PC
PC -> PCDB : DocChiTiet(maPhieuCoc, maCN)
activate PCDB
deactivate PCDB
deactivate PC
XN -> PC : KiemTraCoTheXacNhanThanhToan()
activate PC
deactivate PC
deactivate XN

opt Quan ly xem chung tu
  QL -> MH : Nhan vao chung tu thanh toan
  MH -> MH : xemChungTu()
end

alt Khoan coc hop le
  QL -> MH : Nhan "Xac nhan hop le"
  MH -> MH : moHopThoaiXacNhanHopLe()
  QL -> MH : Xac nhan chot khoan tien coc
  MH -> MH : xacNhanHopLe()
  MH -> XN : XacNhanHopLe(maPhieuCoc, maNhanVienQuanLy)
  activate XN
  XN -> NV : DocPhamVi(maNhanVienQuanLy)
  activate NV
  NV -> NVDB : DocChiTiet(maNhanVienQuanLy)
  activate NVDB
  deactivate NVDB
  deactivate NV
  XN -> PC : DocChiTietChoCapNhat(maPhieuCoc, maCN)
  activate PC
  PC -> PCDB : DocChiTietChoCapNhat(maPhieuCoc, maCN)
  activate PCDB
deactivate PCDB
deactivate PC
  XN -> PC : KiemTraCoTheXacNhanThanhToan()
  activate PC
deactivate PC
  XN -> P : DocChiTiet(maPhong)
  activate P
  P -> PDB : DocChiTiet(maPhong)
  activate PDB
deactivate PDB
deactivate P
  XN -> P : XacNhanDatCoc(maGiuongs)
  activate P
  loop Moi giuong cua phieu coc
    P -> G : XacNhanDaCoc(maPhong)
    activate G
    deactivate G
  end
deactivate P
  XN -> PT : TaoChoTienCoc(phieuCoc, maNhanVienQuanLy, thoiGian)
  activate PT
deactivate PT
  XN -> PC : XacNhanThanhToan()
  activate PC
deactivate PC
  XN -> PC : CapNhatXacNhanThanhToan()
  activate PC
  PC -> PCDB : CapNhatXacNhanThanhToan(phieu)
  activate PCDB
deactivate PCDB
deactivate PC
  XN -> PT : Them()
  activate PT
  PT -> PTDB : Them(phieuThu)
  activate PTDB
deactivate PTDB
deactivate PT
  XN -> P : CapNhatDatCoc()
  activate P
  P -> PDB : CapNhatDatCoc(phong)
  activate PDB
deactivate PDB
deactivate P
deactivate XN
else Chung tu can bo sung
  QL -> MH : Nhan "Yeu cau bo sung"
  MH -> MH : moHopThoaiYeuCauBoSung()
  QL -> MH : Nhap ly do va nhan "Gui yeu cau"
  MH -> MH : yeuCauBoSung(lyDo)
  MH -> XN : YeuCauBoSung(maPhieuCoc, lyDo, maNV)
  activate XN
  XN -> NV : DocPhamVi(maNV)
  activate NV
  NV -> NVDB : DocChiTiet(maNV)
  activate NVDB
  deactivate NVDB
  deactivate NV
  XN -> PC : DocChiTietChoCapNhat(maPhieuCoc, maCN)
  activate PC
  PC -> PCDB : DocChiTietChoCapNhat(maPhieuCoc, maCN)
  activate PCDB
deactivate PCDB
deactivate PC
  XN -> PC : YeuCauBoSung(lyDo, thoiDiemYeuCau, thoiHanThanhToan)
  activate PC
deactivate PC
  XN -> PC : CapNhatYeuCauBoSung()
  activate PC
  PC -> PCDB : CapNhatYeuCauBoSung(phieu)
  activate PCDB
deactivate PCDB
deactivate PC
deactivate XN
end

deactivate MH
@enduml
