@startuml
title SO DO TUAN TU - XET DUYET HO SO NHAN PHONG
hide footbox
autonumber 1 1
skinparam shadowing false
actor "Quan ly" as QL
box "GUI" #D5F5D3
boundary ": MHXetDuyetHoSo" as MH
end box
box "BUS" #FCF3CF
control ": XetDuyetHoSo" as UC
control ": PhieuCoc" as PC
control ": ThanhVienDangKy" as TV
control ": KhachHang" as KH
control ": Phong" as P
control ": Giuong" as G
end box
box "DB" #D6EAF8
entity ": PhieuCocDB" as PCDB
entity ": ThanhVienDangKyDB" as TVDB
entity ": KhachHangDB" as KHDB
entity ": GiuongDB" as GDB
end box

QL -> MH : Chon chuc nang "Xet duyet ho so"
activate MH
MH -> MH : taiDanhSachHoSoChoDuyet()
MH -> UC : LayDanhSachChoDuyet(tuKhoa)
activate UC
UC -> PC : LayDanhSachChoDuyet(tuKhoa)
activate PC
PC -> PCDB : LayDanhSachChoDuyet(tuKhoa)
activate PCDB
deactivate PCDB
deactivate PC
deactivate UC

QL -> MH : Chon ho so cho duyet
MH -> MH : clickChonHoSo()
MH -> UC : LayChiTiet(maPhieuCoc)
activate UC
UC -> PC : LayChiTietChoDuyet(maPhieuCoc)
activate PC
PC -> PCDB : LayChiTietChoDuyet(maPhieuCoc)
activate PCDB
deactivate PCDB
deactivate PC
deactivate UC
opt Quan ly xem chi tiet thanh vien
  QL -> MH : Nhan "Xem chi tiet"
  MH -> MH : clickXemChiTietThanhVien()
end

alt Duyet toan bo ho so
  QL -> MH : Nhan "Duyet toan bo"
  MH -> MH : clickDuyetToanBo()
  MH -> UC : DuyetToanBo(maPhieuCoc, maNV)
  activate UC
  UC -> PC : LayChiTietChoDuyet(maPhieuCoc)
  activate PC
  PC -> PCDB : LayChiTietChoDuyet(maPhieuCoc)
  activate PCDB
  deactivate PCDB
  PC -> PC : KiemTraCoTheXetDuyet()
  deactivate PC
  UC -> TV : KiemTraTonTaiDaiDien(maPhieuCoc)
  activate TV
  TV -> TVDB : GetByMaPhieuCoc(maPhieuCoc)
  activate TVDB
  deactivate TVDB
  deactivate TV
  UC -> KH : LayDanhSachKhachTheoPhieuCoc(maPhieuCoc)
  activate KH
  KH -> KHDB : GetByMaPhieuCoc(maPhieuCoc)
  activate KHDB
  deactivate KHDB
  deactivate KH
  UC -> P : KiemTraSucChua(soLuongThanhVien, soGiuongThue, sucChuaPhong, hinhThucThue)
  activate P
  P -> P : KiemTraGioiTinhChoPhep(dsKhach)
  deactivate P
  UC -> TV : DuyetTatCaThanhVien(maPhieuCoc)
  activate TV
  TV -> TVDB : UpdateTatCaTrangThaiDuyet(maPhieuCoc, "HopLe")
  activate TVDB
  deactivate TVDB
  deactivate TV
  UC -> PC : CapNhatTrangThaiDaDuyet()
  activate PC
  deactivate PC
  UC -> PC : CapNhatTrangThaiDaDuyetDB()
  activate PC
  PC -> PCDB : CapNhatDaDuyet(phieuCoc)
  activate PCDB
  deactivate PCDB
  deactivate PC
  UC -> G : CapNhatDanhSachDaCoc(dsMaGiuong)
  activate G
  G -> GDB : UpdateTrangThaiBatch(dsMaGiuong, "DaCoc")
  activate GDB
  deactivate GDB
  deactivate G
  deactivate UC
else Tu choi mot thanh vien
  QL -> MH : Nhan "Tu choi" tai thanh vien
  MH -> MH : clickTuChoiThanhVien()
  MH -> UC : TuChoiThanhVien(maPhieuCoc, maKH)
  activate UC
  UC -> PC : DocChiTiet(maPhieuCoc)
  activate PC
  PC -> PCDB : DocChiTiet(maPhieuCoc)
  activate PCDB
  deactivate PCDB
  PC -> PC : KiemTraCoTheXetDuyet()
  deactivate PC
  UC -> TV : LayDanhSachThanhVien(maPhieuCoc)
  activate TV
  TV -> TVDB : GetByMaPhieuCoc(maPhieuCoc)
  activate TVDB
  deactivate TVDB
  deactivate TV
  UC -> TV : DanhDauTuChoi(maPhieuCoc, maKH)
  activate TV
  TV -> TVDB : UpdateTrangThaiDuyet(maPhieuCoc, maKH, "TuChoi")
  activate TVDB
  deactivate TVDB
  deactivate TV
  deactivate UC
else Hoan tac tu choi thanh vien
  QL -> MH : Nhan "Hoan tac" tai thanh vien
  MH -> MH : clickHoanTac()
  MH -> UC : HoanTacThanhVien(maPhieuCoc, maKH)
  activate UC
  UC -> PC : DocChiTiet(maPhieuCoc)
  activate PC
  PC -> PCDB : DocChiTiet(maPhieuCoc)
  activate PCDB
  deactivate PCDB
  deactivate PC
  UC -> TV : HoanTac(maPhieuCoc, maKH)
  activate TV
  TV -> TVDB : UpdateTrangThaiDuyet(maPhieuCoc, maKH, "ChoDuyet")
  activate TVDB
  deactivate TVDB
  deactivate TV
  deactivate UC
else Duyet cac thanh vien con lai
  QL -> MH : Nhan "Duyet thanh vien con lai"
  MH -> MH : clickDuyetThanhVienConLai()
  MH -> UC : DuyetThanhVienConLai(maPhieuCoc, maNV)
  activate UC
  UC -> TV : DuyetThanhVienConLai(maPhieuCoc)
  activate TV
  TV -> TVDB : UpdateThanhVienConLaiHopLe(maPhieuCoc)
  activate TVDB
  deactivate TVDB
  deactivate TV
  UC -> TV : DemThanhVienHopLe(maPhieuCoc)
  activate TV
  TV -> TVDB : CountThanhVienHopLe(maPhieuCoc)
  activate TVDB
  deactivate TVDB
  deactivate TV
  UC -> PC : CapNhatTrangThaiDaDuyet()
  activate PC
  deactivate PC
  UC -> PC : CapNhatTrangThaiDaDuyetDB()
  activate PC
  PC -> PCDB : CapNhatDaDuyet(phieuCoc)
  activate PCDB
  deactivate PCDB
  deactivate PC
  UC -> G : CapNhatDanhSachDaCoc(dsMaGiuong)
  activate G
  G -> GDB : UpdateTrangThaiBatch(dsMaGiuong, "DaCoc")
  activate GDB
  deactivate GDB
  deactivate G
  deactivate UC
else Tu choi toan bo ho so
  QL -> MH : Nhan "Tu choi ho so"
  MH -> MH : clickTuChoiHoSo()
  MH -> UC : TuChoiHoSo(maPhieuCoc, maNV)
  activate UC
  UC -> PC : LayChiTietChoDuyet(maPhieuCoc)
  activate PC
  PC -> PCDB : LayChiTietChoDuyet(maPhieuCoc)
  activate PCDB
  deactivate PCDB
  deactivate PC
  UC -> TV : TuChoiTatCaThanhVien(maPhieuCoc)
  activate TV
  TV -> TVDB : UpdateTatCaTrangThaiDuyet(maPhieuCoc, "TuChoi")
  activate TVDB
  deactivate TVDB
  deactivate TV
  UC -> PC : CapNhatTrangThaiDaHuy()
  activate PC
  deactivate PC
  UC -> PC : CapNhatTrangThaiDaHuyDB()
  activate PC
  PC -> PCDB : CapNhatDaHuy(phieuCoc)
  activate PCDB
  deactivate PCDB
  deactivate PC
  UC -> G : CapNhatDanhSachTrong(dsMaGiuong)
  activate G
  G -> GDB : UpdateTrangThaiBatch(dsMaGiuong, "Trong")
  activate GDB
  deactivate GDB
  deactivate G
  deactivate UC
end
deactivate MH
@enduml
