/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ResidenceRouteImport } from './routes/residence'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as ApprovalRouteImport } from './routes/approval'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountantRouteImport } from './routes/accountant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as AccountantIndexRouteImport } from './routes/accountant.index'
import { Route as SaleTraCuuHopDongRouteImport } from './routes/sale.tra-cuu-hop-dong'
import { Route as SaleLapHopDongRouteImport } from './routes/sale.lap-hop-dong'
import { Route as SaleHoSoLuuTruRouteImport } from './routes/sale.ho-so-luu-tru'
import { Route as SaleDashboardRouteImport } from './routes/sale.dashboard'
import { Route as ManagerTraCuuHopDongRouteImport } from './routes/manager.tra-cuu-hop-dong'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerHandoverRouteImport } from './routes/manager.handover'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as ManagerContractsRouteImport } from './routes/manager.contracts'
import { Route as ManagerApprovalRouteImport } from './routes/manager.approval'
import { Route as AccountantTransactionsRouteImport } from './routes/accountant.transactions'
import { Route as AccountantTraCuuHopDongRouteImport } from './routes/accountant.tra-cuu-hop-dong'
import { Route as AccountantPaymentsRouteImport } from './routes/accountant.payments'

const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenceRoute = ResidenceRouteImport.update({
  id: '/residence',
  path: '/residence',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRoute = ApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRoute = AccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const AccountantIndexRoute = AccountantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountantRoute,
} as any)
const SaleTraCuuHopDongRoute = SaleTraCuuHopDongRouteImport.update({
  id: '/tra-cuu-hop-dong',
  path: '/tra-cuu-hop-dong',
  getParentRoute: () => SaleRoute,
} as any)
const SaleLapHopDongRoute = SaleLapHopDongRouteImport.update({
  id: '/lap-hop-dong',
  path: '/lap-hop-dong',
  getParentRoute: () => SaleRoute,
} as any)
const SaleHoSoLuuTruRoute = SaleHoSoLuuTruRouteImport.update({
  id: '/ho-so-luu-tru',
  path: '/ho-so-luu-tru',
  getParentRoute: () => SaleRoute,
} as any)
const SaleDashboardRoute = SaleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SaleRoute,
} as any)
const ManagerTraCuuHopDongRoute = ManagerTraCuuHopDongRouteImport.update({
  id: '/tra-cuu-hop-dong',
  path: '/tra-cuu-hop-dong',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerHandoverRoute = ManagerHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerContractsRoute = ManagerContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerApprovalRoute = ManagerApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => ManagerRoute,
} as any)
const AccountantTransactionsRoute = AccountantTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AccountantRoute,
} as any)
const AccountantTraCuuHopDongRoute = AccountantTraCuuHopDongRouteImport.update({
  id: '/tra-cuu-hop-dong',
  path: '/tra-cuu-hop-dong',
  getParentRoute: () => AccountantRoute,
} as any)
const AccountantPaymentsRoute = AccountantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRouteWithChildren
  '/admin': typeof AdminRoute
  '/approval': typeof ApprovalRoute
  '/contract': typeof ContractRoute
  '/manager': typeof ManagerRouteWithChildren
  '/residence': typeof ResidenceRoute
  '/sale': typeof SaleRouteWithChildren
  '/accountant/payments': typeof AccountantPaymentsRoute
  '/accountant/tra-cuu-hop-dong': typeof AccountantTraCuuHopDongRoute
  '/accountant/transactions': typeof AccountantTransactionsRoute
  '/manager/approval': typeof ManagerApprovalRoute
  '/manager/contracts': typeof ManagerContractsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/handover': typeof ManagerHandoverRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/tra-cuu-hop-dong': typeof ManagerTraCuuHopDongRoute
  '/sale/dashboard': typeof SaleDashboardRoute
  '/sale/ho-so-luu-tru': typeof SaleHoSoLuuTruRoute
  '/sale/lap-hop-dong': typeof SaleLapHopDongRoute
  '/sale/tra-cuu-hop-dong': typeof SaleTraCuuHopDongRoute
  '/accountant/': typeof AccountantIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approval': typeof ApprovalRoute
  '/contract': typeof ContractRoute
  '/residence': typeof ResidenceRoute
  '/sale': typeof SaleRouteWithChildren
  '/accountant/payments': typeof AccountantPaymentsRoute
  '/accountant/tra-cuu-hop-dong': typeof AccountantTraCuuHopDongRoute
  '/accountant/transactions': typeof AccountantTransactionsRoute
  '/manager/approval': typeof ManagerApprovalRoute
  '/manager/contracts': typeof ManagerContractsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/handover': typeof ManagerHandoverRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/tra-cuu-hop-dong': typeof ManagerTraCuuHopDongRoute
  '/sale/dashboard': typeof SaleDashboardRoute
  '/sale/ho-so-luu-tru': typeof SaleHoSoLuuTruRoute
  '/sale/lap-hop-dong': typeof SaleLapHopDongRoute
  '/sale/tra-cuu-hop-dong': typeof SaleTraCuuHopDongRoute
  '/accountant': typeof AccountantIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRouteWithChildren
  '/admin': typeof AdminRoute
  '/approval': typeof ApprovalRoute
  '/contract': typeof ContractRoute
  '/manager': typeof ManagerRouteWithChildren
  '/residence': typeof ResidenceRoute
  '/sale': typeof SaleRouteWithChildren
  '/accountant/payments': typeof AccountantPaymentsRoute
  '/accountant/tra-cuu-hop-dong': typeof AccountantTraCuuHopDongRoute
  '/accountant/transactions': typeof AccountantTransactionsRoute
  '/manager/approval': typeof ManagerApprovalRoute
  '/manager/contracts': typeof ManagerContractsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/handover': typeof ManagerHandoverRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/tra-cuu-hop-dong': typeof ManagerTraCuuHopDongRoute
  '/sale/dashboard': typeof SaleDashboardRoute
  '/sale/ho-so-luu-tru': typeof SaleHoSoLuuTruRoute
  '/sale/lap-hop-dong': typeof SaleLapHopDongRoute
  '/sale/tra-cuu-hop-dong': typeof SaleTraCuuHopDongRoute
  '/accountant/': typeof AccountantIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant'
    | '/admin'
    | '/approval'
    | '/contract'
    | '/manager'
    | '/residence'
    | '/sale'
    | '/accountant/payments'
    | '/accountant/tra-cuu-hop-dong'
    | '/accountant/transactions'
    | '/manager/approval'
    | '/manager/contracts'
    | '/manager/dashboard'
    | '/manager/handover'
    | '/manager/reports'
    | '/manager/tra-cuu-hop-dong'
    | '/sale/dashboard'
    | '/sale/ho-so-luu-tru'
    | '/sale/lap-hop-dong'
    | '/sale/tra-cuu-hop-dong'
    | '/accountant/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approval'
    | '/contract'
    | '/residence'
    | '/sale'
    | '/accountant/payments'
    | '/accountant/tra-cuu-hop-dong'
    | '/accountant/transactions'
    | '/manager/approval'
    | '/manager/contracts'
    | '/manager/dashboard'
    | '/manager/handover'
    | '/manager/reports'
    | '/manager/tra-cuu-hop-dong'
    | '/sale/dashboard'
    | '/sale/ho-so-luu-tru'
    | '/sale/lap-hop-dong'
    | '/sale/tra-cuu-hop-dong'
    | '/accountant'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/accountant'
    | '/admin'
    | '/approval'
    | '/contract'
    | '/manager'
    | '/residence'
    | '/sale'
    | '/accountant/payments'
    | '/accountant/tra-cuu-hop-dong'
    | '/accountant/transactions'
    | '/manager/approval'
    | '/manager/contracts'
    | '/manager/dashboard'
    | '/manager/handover'
    | '/manager/reports'
    | '/manager/tra-cuu-hop-dong'
    | '/sale/dashboard'
    | '/sale/ho-so-luu-tru'
    | '/sale/lap-hop-dong'
    | '/sale/tra-cuu-hop-dong'
    | '/accountant/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantRoute: typeof AccountantRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApprovalRoute: typeof ApprovalRoute
  ContractRoute: typeof ContractRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ResidenceRoute: typeof ResidenceRoute
  SaleRoute: typeof SaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residence': {
      id: '/residence'
      path: '/residence'
      fullPath: '/residence'
      preLoaderRoute: typeof ResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant': {
      id: '/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AccountantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/accountant/': {
      id: '/accountant/'
      path: '/'
      fullPath: '/accountant/'
      preLoaderRoute: typeof AccountantIndexRouteImport
      parentRoute: typeof AccountantRoute
    }
    '/sale/tra-cuu-hop-dong': {
      id: '/sale/tra-cuu-hop-dong'
      path: '/tra-cuu-hop-dong'
      fullPath: '/sale/tra-cuu-hop-dong'
      preLoaderRoute: typeof SaleTraCuuHopDongRouteImport
      parentRoute: typeof SaleRoute
    }
    '/sale/lap-hop-dong': {
      id: '/sale/lap-hop-dong'
      path: '/lap-hop-dong'
      fullPath: '/sale/lap-hop-dong'
      preLoaderRoute: typeof SaleLapHopDongRouteImport
      parentRoute: typeof SaleRoute
    }
    '/sale/ho-so-luu-tru': {
      id: '/sale/ho-so-luu-tru'
      path: '/ho-so-luu-tru'
      fullPath: '/sale/ho-so-luu-tru'
      preLoaderRoute: typeof SaleHoSoLuuTruRouteImport
      parentRoute: typeof SaleRoute
    }
    '/sale/dashboard': {
      id: '/sale/dashboard'
      path: '/dashboard'
      fullPath: '/sale/dashboard'
      preLoaderRoute: typeof SaleDashboardRouteImport
      parentRoute: typeof SaleRoute
    }
    '/manager/tra-cuu-hop-dong': {
      id: '/manager/tra-cuu-hop-dong'
      path: '/tra-cuu-hop-dong'
      fullPath: '/manager/tra-cuu-hop-dong'
      preLoaderRoute: typeof ManagerTraCuuHopDongRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/handover': {
      id: '/manager/handover'
      path: '/handover'
      fullPath: '/manager/handover'
      preLoaderRoute: typeof ManagerHandoverRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/contracts': {
      id: '/manager/contracts'
      path: '/contracts'
      fullPath: '/manager/contracts'
      preLoaderRoute: typeof ManagerContractsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/approval': {
      id: '/manager/approval'
      path: '/approval'
      fullPath: '/manager/approval'
      preLoaderRoute: typeof ManagerApprovalRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/accountant/transactions': {
      id: '/accountant/transactions'
      path: '/transactions'
      fullPath: '/accountant/transactions'
      preLoaderRoute: typeof AccountantTransactionsRouteImport
      parentRoute: typeof AccountantRoute
    }
    '/accountant/tra-cuu-hop-dong': {
      id: '/accountant/tra-cuu-hop-dong'
      path: '/tra-cuu-hop-dong'
      fullPath: '/accountant/tra-cuu-hop-dong'
      preLoaderRoute: typeof AccountantTraCuuHopDongRouteImport
      parentRoute: typeof AccountantRoute
    }
    '/accountant/payments': {
      id: '/accountant/payments'
      path: '/payments'
      fullPath: '/accountant/payments'
      preLoaderRoute: typeof AccountantPaymentsRouteImport
      parentRoute: typeof AccountantRoute
    }
  }
}

interface AccountantRouteChildren {
  AccountantPaymentsRoute: typeof AccountantPaymentsRoute
  AccountantTraCuuHopDongRoute: typeof AccountantTraCuuHopDongRoute
  AccountantTransactionsRoute: typeof AccountantTransactionsRoute
  AccountantIndexRoute: typeof AccountantIndexRoute
}

const AccountantRouteChildren: AccountantRouteChildren = {
  AccountantPaymentsRoute: AccountantPaymentsRoute,
  AccountantTraCuuHopDongRoute: AccountantTraCuuHopDongRoute,
  AccountantTransactionsRoute: AccountantTransactionsRoute,
  AccountantIndexRoute: AccountantIndexRoute,
}

const AccountantRouteWithChildren = AccountantRoute._addFileChildren(
  AccountantRouteChildren,
)

interface ManagerRouteChildren {
  ManagerApprovalRoute: typeof ManagerApprovalRoute
  ManagerContractsRoute: typeof ManagerContractsRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerHandoverRoute: typeof ManagerHandoverRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerTraCuuHopDongRoute: typeof ManagerTraCuuHopDongRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerApprovalRoute: ManagerApprovalRoute,
  ManagerContractsRoute: ManagerContractsRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerHandoverRoute: ManagerHandoverRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerTraCuuHopDongRoute: ManagerTraCuuHopDongRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface SaleRouteChildren {
  SaleDashboardRoute: typeof SaleDashboardRoute
  SaleHoSoLuuTruRoute: typeof SaleHoSoLuuTruRoute
  SaleLapHopDongRoute: typeof SaleLapHopDongRoute
  SaleTraCuuHopDongRoute: typeof SaleTraCuuHopDongRoute
}

const SaleRouteChildren: SaleRouteChildren = {
  SaleDashboardRoute: SaleDashboardRoute,
  SaleHoSoLuuTruRoute: SaleHoSoLuuTruRoute,
  SaleLapHopDongRoute: SaleLapHopDongRoute,
  SaleTraCuuHopDongRoute: SaleTraCuuHopDongRoute,
}

const SaleRouteWithChildren = SaleRoute._addFileChildren(SaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantRoute: AccountantRouteWithChildren,
  AdminRoute: AdminRoute,
  ApprovalRoute: ApprovalRoute,
  ContractRoute: ContractRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ResidenceRoute: ResidenceRoute,
  SaleRoute: SaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
